In [1]:
import pandas as pd
import numpy as np
from Bio import SeqIO # for handling fastas
import glob  # To handle multiple files
import os

In [11]:
#read in df....(dataframe1 from the baltic 
df = pd.read_csv('../../sample_data/2026-04-02-fullnortham-meta-w-gtypes-ctys.tsv', sep='\t')
df

,Unnamed: 0.1,Unnamed: 0,strain,date,region,country,division,location,host,subtype,...,id,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state,Genotype
0,0,0,A/TrumpeterSwan/BritishColumbia/AIVPHL775/2022,2022-11-28,North America,Canada,British Columbia,British Columbia,Avian,h5n1,...,AIVPHL775,trumpeterswan,wild,Anseriformes,NaN,wild,non_PA,NaN,non-border,NaN
1,1,1,A/Americanwigeon/NorthCarolina/AH0182517/2022,2022-01-08,North America,Usa,North Carolina,North Carolina,Avian,h5n1,...,AH0182517,American wigeon,wild,Anseriformes,NaN,wild,non_PA,wild,non-border,A1
2,2,2,A/turkey/BritishColumbia/AIVPHL128/2022,2022-05-18,North America,Canada,British Columbia,British Columbia,Avian,h5n1,...,AIVPHL128,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border,B2.1
3,3,3,A/turkey/Minnesota/USDA011789003/2022,2022-04-17,North America,Usa,Minnesota,Minnesota,Avian,h5n1,...,USDA011789003,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border,B2.1
4,4,4,A/BlackVulture/Florida/USDA012636001/2022,2022-04-22,North America,Usa,Florida,Florida,Avian,h5n1,...,USDA012636001,Black Vulture,wild,Raptor,NaN,wild,non_PA,NaN,non-border,B1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12709,12709,12709,A/red_tailedhawk/Pennsylvania/rth_w4/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,rth_w4,red_tailed hawk,wild,NaN,Erie,wild,Pennsylvania,NaN,PA,NaN
12710,12710,12710,A/snowyowl/Pennsylvania/so_w1/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,so_w1,snowy owl,wild,NaN,Erie,wild,Pennsylvania,NaN,PA,NaN
12711,12711,12711,A/turkeyvulture/Pennsylvania/tv_w2/2025,2025-03-05,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,tv_w2,turkey vulture,wild,NaN,Erie,wild,Pennsylvania,NaN,PA,NaN
12712,12712,12712,A/turkeyvulture/Pennsylvania/tv_w3/2025,2025-03-24,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,tv_w3,turkey vulture,wild,NaN,Cumberland,wild,Pennsylvania,NaN,PA,NaN
12713,12713,12713,A/white_wingedscoter/Pennsylvania/wws_w1/2022,2022-12-19,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,wws_w1,white-winged scoter,wild,Anseriformes,Erie,wild,Pennsylvania,NaN,PA,NaN

In [12]:
##fixing border states!!!
border_states = ['New York', 'New Jersey', 'Delaware', 'Ohio', 'Maryland', 'West Virginia']

df['border_state'] = np.select(
    [df['division'] == 'Pennsylvania', df['division'].isin(border_states)],
    ['PA', 'border'],
    default='non-border'
)

In [13]:
df['border_state'].value_counts()

border_state
non-border    11595
border          752
PA              367
Name: count, dtype: int64

In [28]:
df.to_csv('../phylo/2026-04-02-fullnortham-meta-w-gtypes-ctys.tsv', sep='\t')

In [14]:
df = df[df['Genotype'] == 'D1.1']
df

,Unnamed: 0.1,Unnamed: 0,strain,date,region,country,division,location,host,subtype,...,id,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state,Genotype
3773,3773,3773,A/guineafowl/Washington/24030328002/2024,2024-10-15,North America,Usa,Washington,Washington,Avian,h5n1,...,24030328002,guineafowl,domestic,Galliformes,NaN,domestic,non_PA,unknown,non-border,D1.1
3798,3798,3798,A/chicken/Oklahoma/24036668001/2024,2024-12-08,North America,Usa,Oklahoma,Oklahoma,Avian,h5n1,...,24036668001,chicken,domestic,Galliformes,NaN,domestic,non_PA,domestic,non-border,D1.1
3924,3924,3924,A/woodduck/USA/001096002/2025,2025-XX-XX,North America,Usa,Usa,Usa,Avian,h5n1,...,1096002,woodduck,wild,Anseriformes,NaN,wild,non_PA,NaN,non-border,D1.1
3986,3986,3986,A/chicken/Alabama/24037981002/2024,2024-12-13,North America,Usa,Alabama,Alabama,Avian,h5n1,...,24037981002,chicken,domestic,Galliformes,NaN,domestic,non_PA,domestic,non-border,D1.1
4134,4134,4134,A/canadagoose/USA/000616002/2025,2025-XX-XX,North America,Usa,Usa,Usa,Avian,h5n1,...,616002,canadagoose,unknown,Anseriformes,NaN,NaN,non_PA,NaN,non-border,D1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12691,12691,12691,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Usa,Kentucky,NaN,Avian,h5n1,...,NaN,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border,D1.1
12692,12692,12692,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Usa,Mississippi,NaN,Avian,h5n1,...,NaN,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border,D1.1
12698,12698,12698,A/chicken/Pennsylvania/c_com2/2025,2025-03-16,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,c_com2,chicken,commercial,Galliformes,Lebanon,domestic,Pennsylvania,NaN,PA,D1.1
12701,12701,12701,A/chicken/Pennsylvania/c_com5/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,c_com5,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA,D1.1
12702,12702,12702,A/chicken/Pennsylvania/c_com6/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,c_com6,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA,D1.1

In [15]:
df['division'].unique()

array(['Washington', 'Oklahoma', 'Usa', 'Alabama', 'Nebraska',
       'South Dakota', 'California', 'Iowa', 'Mississippi', 'Kansas',
       'Arizona', 'Wisconsin', 'Arkansas', 'Oregon', 'Alaska',
       'Minnesota', 'British Columbia', 'Missouri', 'Utah', 'Tennessee',
       'Illinois', 'Idaho', 'Louisiana', 'North Dakota', 'Colorado',
       'Ohio', 'Pennsylvania', 'Florida', 'New York', 'South Carolina',
       'Connecticut', 'Kentucky', 'Massachusetts', 'Michigan',
       'West Virginia', 'Delaware', 'Georgia', 'Indiana', 'Maryland',
       'Maine', 'Montana', 'North Carolina', 'New Jersey', 'New Mexico',
       'Nevada', 'Virginia', 'Wyoming', 'Durango', 'New Hampshire',
       'Vermont', 'Sonora'], dtype=object)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 900 entries, 3773 to 12702
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0.1     900 non-null    int64
 1   Unnamed: 0       900 non-null    int64
 2   strain           900 non-null    object
 3   date             900 non-null    object
 4   region           900 non-null    object
 5   country          900 non-null    object
 6   division         900 non-null    object
 7   location         256 non-null    object
 8   host             900 non-null    object
 9   subtype          900 non-null    object
 10  originating_lab  256 non-null    object
 11  submitting_lab   256 non-null    object
 12  h5_label_clade   900 non-null    object
 13  animal           256 non-null    object
 14  order            894 non-null    object
 15  flyway           865 non-null    object
 16  geo_region_na    221 non-null    object
 17  id               256 non-null    object
 18  species          900 non-null    object
 19  domestic_status  900 non-null    object
 20  species_group    256 non-null    object
 21  county           26 non-null     object
 22  wild_dom_lbm     663 non-null    object
 23  pa_status        900 non-null    object
 24  domesticstatus   185 non-null    object
 25  border_state     900 non-null    object
 26  Genotype         900 non-null    object
dtypes: int64(2), object(25)
memory usage: 196.9+ KB

In [17]:
regions = pd.read_csv('flyway_regions.csv')
regions

            location           flyway    geo_region_na
0            Vermont  Atlantic Flyway        Northeast
1        Connecticut  Atlantic Flyway        Northeast
2           Delaware  Atlantic Flyway            South
3            Florida  Atlantic Flyway            South
4            Georgia  Atlantic Flyway            South
..               ...              ...              ...
58             Idaho   Pacific Flyway             West
59  British Columbia   Pacific Flyway           Canada
60          Honduras   Central Flyway  Central America
61        Costa Rica   Central Flyway  Central America
62            Panama   Central Flyway  Central America

[63 rows x 3 columns]

In [18]:
regions.rename(columns={'location':'division'},inplace=True)

In [8]:
# # df.drop(columns=['geo_region_na'], inplace=True)
# df = pd.merge(df, regions[['division', 'geo_region_na']], how='left', on=['division'])
# df

,Unnamed: 0.1,Unnamed: 0,strain,date,region,country,division,location,host,subtype,...,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state,Genotype,geo_region_na_y
0,3773,3773,A/guineafowl/Washington/24030328002/2024,2024-10-15,North America,Usa,Washington,Washington,Avian,h5n1,...,guineafowl,domestic,Galliformes,NaN,domestic,non_PA,unknown,non-border,D1.1,West
1,3798,3798,A/chicken/Oklahoma/24036668001/2024,2024-12-08,North America,Usa,Oklahoma,Oklahoma,Avian,h5n1,...,chicken,domestic,Galliformes,NaN,domestic,non_PA,domestic,non-border,D1.1,South
2,3924,3924,A/woodduck/USA/001096002/2025,2025-XX-XX,North America,Usa,Usa,Usa,Avian,h5n1,...,woodduck,wild,Anseriformes,NaN,wild,non_PA,NaN,non-border,D1.1,NaN
3,3986,3986,A/chicken/Alabama/24037981002/2024,2024-12-13,North America,Usa,Alabama,Alabama,Avian,h5n1,...,chicken,domestic,Galliformes,NaN,domestic,non_PA,domestic,non-border,D1.1,South
4,4134,4134,A/canadagoose/USA/000616002/2025,2025-XX-XX,North America,Usa,Usa,Usa,Avian,h5n1,...,canadagoose,unknown,Anseriformes,NaN,NaN,non_PA,NaN,non-border,D1.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,12691,12691,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Usa,Kentucky,NaN,Avian,h5n1,...,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border,D1.1,South
896,12692,12692,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Usa,Mississippi,NaN,Avian,h5n1,...,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border,D1.1,South
897,12698,12698,A/chicken/Pennsylvania/c_com2/2025,2025-03-16,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,chicken,commercial,Galliformes,Lebanon,domestic,Pennsylvania,NaN,PA,D1.1,Northeast
898,12701,12701,A/chicken/Pennsylvania/c_com5/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA,D1.1,Northeast
899,12702,12702,A/chicken/Pennsylvania/c_com6/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA,D1.1,Northeast

In [10]:
df

,Unnamed: 0.1,Unnamed: 0,strain,date,region,country,division,location,host,subtype,...,id,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state,Genotype
3773,3773,3773,A/guineafowl/Washington/24030328002/2024,2024-10-15,North America,Usa,Washington,Washington,Avian,h5n1,...,24030328002,guineafowl,domestic,Galliformes,NaN,domestic,non_PA,unknown,non-border,D1.1
3798,3798,3798,A/chicken/Oklahoma/24036668001/2024,2024-12-08,North America,Usa,Oklahoma,Oklahoma,Avian,h5n1,...,24036668001,chicken,domestic,Galliformes,NaN,domestic,non_PA,domestic,non-border,D1.1
3924,3924,3924,A/woodduck/USA/001096002/2025,2025-XX-XX,North America,Usa,Usa,Usa,Avian,h5n1,...,1096002,woodduck,wild,Anseriformes,NaN,wild,non_PA,NaN,non-border,D1.1
3986,3986,3986,A/chicken/Alabama/24037981002/2024,2024-12-13,North America,Usa,Alabama,Alabama,Avian,h5n1,...,24037981002,chicken,domestic,Galliformes,NaN,domestic,non_PA,domestic,non-border,D1.1
4134,4134,4134,A/canadagoose/USA/000616002/2025,2025-XX-XX,North America,Usa,Usa,Usa,Avian,h5n1,...,616002,canadagoose,unknown,Anseriformes,NaN,NaN,non_PA,NaN,non-border,D1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12691,12691,12691,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Usa,Kentucky,NaN,Avian,h5n1,...,NaN,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border,D1.1
12692,12692,12692,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Usa,Mississippi,NaN,Avian,h5n1,...,NaN,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border,D1.1
12698,12698,12698,A/chicken/Pennsylvania/c_com2/2025,2025-03-16,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,c_com2,chicken,commercial,Galliformes,Lebanon,domestic,Pennsylvania,NaN,PA,D1.1
12701,12701,12701,A/chicken/Pennsylvania/c_com5/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,c_com5,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA,D1.1
12702,12702,12702,A/chicken/Pennsylvania/c_com6/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,c_com6,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA,D1.1

In [19]:
df['states_grouped'] = np.select(
    [df['division'] == 'Pennsylvania', df['division'] == 'New York', df['division'] == 'New Jersey'],
    ['PA', 'NY', 'NJ'],
    default=df['geo_region_na']
)
df

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_52138/2666518645.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['states_grouped'] = np.select(

,Unnamed: 0.1,Unnamed: 0,strain,date,region,country,division,location,host,subtype,...,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state,Genotype,states_grouped
3773,3773,3773,A/guineafowl/Washington/24030328002/2024,2024-10-15,North America,Usa,Washington,Washington,Avian,h5n1,...,guineafowl,domestic,Galliformes,NaN,domestic,non_PA,unknown,non-border,D1.1,West
3798,3798,3798,A/chicken/Oklahoma/24036668001/2024,2024-12-08,North America,Usa,Oklahoma,Oklahoma,Avian,h5n1,...,chicken,domestic,Galliformes,NaN,domestic,non_PA,domestic,non-border,D1.1,South
3924,3924,3924,A/woodduck/USA/001096002/2025,2025-XX-XX,North America,Usa,Usa,Usa,Avian,h5n1,...,woodduck,wild,Anseriformes,NaN,wild,non_PA,NaN,non-border,D1.1,NaN
3986,3986,3986,A/chicken/Alabama/24037981002/2024,2024-12-13,North America,Usa,Alabama,Alabama,Avian,h5n1,...,chicken,domestic,Galliformes,NaN,domestic,non_PA,domestic,non-border,D1.1,South
4134,4134,4134,A/canadagoose/USA/000616002/2025,2025-XX-XX,North America,Usa,Usa,Usa,Avian,h5n1,...,canadagoose,unknown,Anseriformes,NaN,NaN,non_PA,NaN,non-border,D1.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12691,12691,12691,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Usa,Kentucky,NaN,Avian,h5n1,...,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border,D1.1,NaN
12692,12692,12692,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Usa,Mississippi,NaN,Avian,h5n1,...,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border,D1.1,NaN
12698,12698,12698,A/chicken/Pennsylvania/c_com2/2025,2025-03-16,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,chicken,commercial,Galliformes,Lebanon,domestic,Pennsylvania,NaN,PA,D1.1,PA
12701,12701,12701,A/chicken/Pennsylvania/c_com5/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA,D1.1,PA
12702,12702,12702,A/chicken/Pennsylvania/c_com6/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA,D1.1,PA

In [38]:
df['wild_dom_lbm'].unique()

array(['domestic', 'wild', nan, 'unknown', 'lbm'], dtype=object)

In [23]:
df['wild_dom_lbm'] = df['wild_dom_lbm'].fillna("unknown")
df['wild_dom_lbm'].unique()

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_52138/1506635460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wild_dom_lbm'] = df['wild_dom_lbm'].fillna("unknown")

array(['domestic', 'wild', 'unknown', 'lbm'], dtype=object)

In [24]:
##new column called sate-domstat
##if domstat = unknown, then state-domstat = "other
##if domstat = wild, then state-domstat = "wild
##if domstat = lbm OR domestic and states_grouped = PA, then state_domstat = "PA-domestic"
##if domstat = domestic and states-grouped = NY, then state-domstat = NY-domestic"

df["state_domstat"] = np.select(
    [
        df["wild_dom_lbm"].isna() | (df["wild_dom_lbm"] == "unknown"), ##is unknown or NA domstat
        (df["wild_dom_lbm"] == "domestic") & (~df["states_grouped"].isin(["NY", "PA"])), ##not in PA or NY and is domestic
        df["wild_dom_lbm"] == "wild", ##is wild
        (df["wild_dom_lbm"].isin(["lbm", "domestic"])) & (df["states_grouped"] == "PA"), ##lbm or domestic and from PA
        (df["wild_dom_lbm"] == "domestic") & (df["states_grouped"] == "NY") ##domestic NY
    ],
    [
        "other",
        "other",
        "wild",
        "PA_domestic",
        "NY_domestic"
    ],
    default=None
)

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_52138/388732575.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["state_domstat"] = np.select(

In [25]:
df['state_domstat'].value_counts()

state_domstat
other          617
wild           164
PA_domestic     70
NY_domestic     49
Name: count, dtype: int64

In [26]:
df["state_domstat2"] = np.select(
    [
        (df["wild_dom_lbm"] == "unknown") & (~df["states_grouped"].isin(["NY", "PA"])), ##is unknown or NA domstat and not PA or NY
        (df["wild_dom_lbm"] == "domestic") & (~df["states_grouped"].isin(["NY", "PA"])), ##not in PA or NY and is domestic
        df["wild_dom_lbm"] == "wild", ##is wild
        (df["wild_dom_lbm"].isin(["lbm", "domestic"])) & (df["states_grouped"] == "PA"), ##lbm or domestic and from PA
        (df["wild_dom_lbm"] == "domestic") & (df["states_grouped"] == "NY"), ##domestic NY
        (df["wild_dom_lbm"] == "unknown") & (df["states_grouped"] == "NY"), ##unknown NY
        (df["wild_dom_lbm"] == "unknown") & (df["states_grouped"] == "PA") ##unknown NY

    ],
    [
        "other",
        "other",
        "wild",
        "PA_domestic",
        "NY_domestic",
        "NY_unknown",
        "PA_unknown"
    ],
    default=None
)
df['state_domstat2'].value_counts()

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_52138/2323065817.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["state_domstat2"] = np.select(

state_domstat2
other          523
wild           164
PA_domestic     70
PA_unknown      54
NY_domestic     49
NY_unknown      40
Name: count, dtype: int64

In [28]:
df["pa_ny_nj_other"] = np.select(
    [
        (~df["states_grouped"].isin(["NY", "PA","NJ"])), ##is unknown or NA domstat and not PA or NY
    ],
    [
        "other"
    ],
    default=df['states_grouped']
)
df['pa_ny_nj_other'].value_counts()

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_52138/3894751560.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["pa_ny_nj_other"] = np.select(

pa_ny_nj_other
other    596
PA       155
NY       123
NJ        26
Name: count, dtype: int64

In [41]:
# Create a dictionary for quick lookup of metadata by subtree_name
metadata_dict = df.set_index('strain').to_dict(orient='index')

# Process all subtree alignment files in a folder
input_files = glob.glob('aligned_314.fasta')  # Adjust path as needed

for fasta_file in input_files:
    output_file = fasta_file.replace(".fasta", "_w_meta.fasta")
    
    with open(fasta_file, 'r') as input_handle, open(output_file, 'w') as output_handle:
        for record in SeqIO.parse(input_handle, 'fasta'):
            # Find the corresponding metadata (default to 'unknown' if not found)
            metadata = metadata_dict.get(record.id, {'date': 'unknown', 
                                        'wild_dom_lbm': 'unknown', 
                                        'state_domstat':'unknown',
                                        'states_grouped': 'unknown',
                                        'order': 'unknown'})
            # Update the header with all metadata fields
            record.id = f"{record.id}|{metadata['date']}|{metadata['wild_dom_lbm']}|{metadata['state_domstat']}|{metadata['states_grouped']}|{metadata['order']}|"
            record.description = ""  # Clear description to avoid duplicating info
            
            # Write the modified record to the output file
            SeqIO.write(record, output_handle, 'fasta')
    
    print(f"Modified FASTA file saved to {output_file}")

Modified FASTA file saved to aligned_314_w_meta.fasta

In [30]:
# Create a dictionary for quick lookup of metadata by subtree_name for statesgrouped2 and nynypaother
metadata_dict = df.set_index('strain').to_dict(orient='index')

# Process all subtree alignment files in a folder
input_files = glob.glob('aligned_314.fasta')  # Adjust path as needed

for fasta_file in input_files:
    output_file = fasta_file.replace(".fasta", "_w_meta2.fasta")
    
    with open(fasta_file, 'r') as input_handle, open(output_file, 'w') as output_handle:
        for record in SeqIO.parse(input_handle, 'fasta'):
            # Find the corresponding metadata (default to 'unknown' if not found)
            metadata = metadata_dict.get(record.id, {'date': 'unknown', 
                                        'wild_dom_lbm': 'unknown', 
                                        'state_domstat2':'unknown',
                                        'pa_ny_nj_other': 'unknown',
                                        'order': 'unknown'})
            # Update the header with all metadata fields
            record.id = f"{record.id}|{metadata['date']}|{metadata['wild_dom_lbm']}|{metadata['state_domstat2']}|{metadata['pa_ny_nj_other']}|{metadata['order']}|"
            record.description = ""  # Clear description to avoid duplicating info
            
            # Write the modified record to the output file
            SeqIO.write(record, output_handle, 'fasta')
    
    print(f"Modified FASTA file saved to {output_file}")

Modified FASTA file saved to aligned_314_w_meta2.fasta

In [37]:
# Assumes header is the full name, adjust if IDs are formatted differently
fasta_path ="aligned_314.fasta"
fasta_strains = [record.id for record in SeqIO.parse(fasta_path, "fasta")]

# 3. Filter DataFrame using isin()
# This keeps only rows where 'strain_col' is in the fasta_strains list
filtered_df = df[df['strain'].isin(fasta_strains)]
filtered_df

,Unnamed: 0.1,Unnamed: 0,strain,date,region,country,division,location,host,subtype,...,county,wild_dom_lbm,pa_status,domesticstatus,border_state,Genotype,states_grouped,state_domstat,state_domstat2,pa_ny_nj_other
11803,11803,11803,A/chicken/Pennsylvania/c_lbm1/2025,2025-02-20,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
11804,11804,11804,A/chicken/Pennsylvania/c_lbm10/2025,2025-03-11,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
11806,11806,11806,A/chicken/Pennsylvania/c_lbm2/2025,2025-02-20,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
11807,11807,11807,A/chicken/Pennsylvania/c_lbm3/2025,2025-02-20,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
11808,11808,11808,A/chicken/Pennsylvania/c_lbm4/2025,2025-02-20,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12686,12686,12686,a/vulture/md/25001987001original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,...,NaN,wild,non_PA,NaN,border,D1.1,NaN,wild,wild,other
12688,12688,12688,a/vulture/md/25001987003original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,...,NaN,wild,non_PA,NaN,border,D1.1,NaN,wild,wild,other
12698,12698,12698,A/chicken/Pennsylvania/c_com2/2025,2025-03-16,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Lebanon,domestic,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
12701,12701,12701,A/chicken/Pennsylvania/c_com5/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,unknown,domestic,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
12702,12702,12702,A/chicken/Pennsylvania/c_com6/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,unknown,domestic,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA

In [38]:
filtered_df['wild_dom_lbm'].value_counts()

wild_dom_lbm
domestic    114
unknown      96
wild         84
lbm          17
Name: count, dtype: int64

In [39]:
filtered_df = filtered_df[filtered_df['wild_dom_lbm']!="unknown"]
filtered_df

,Unnamed: 0.1,Unnamed: 0,strain,date,region,country,division,location,host,subtype,...,county,wild_dom_lbm,pa_status,domesticstatus,border_state,Genotype,states_grouped,state_domstat,state_domstat2,pa_ny_nj_other
11803,11803,11803,A/chicken/Pennsylvania/c_lbm1/2025,2025-02-20,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
11804,11804,11804,A/chicken/Pennsylvania/c_lbm10/2025,2025-03-11,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
11806,11806,11806,A/chicken/Pennsylvania/c_lbm2/2025,2025-02-20,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
11807,11807,11807,A/chicken/Pennsylvania/c_lbm3/2025,2025-02-20,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
11808,11808,11808,A/chicken/Pennsylvania/c_lbm4/2025,2025-02-20,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Philadelphia,lbm,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12686,12686,12686,a/vulture/md/25001987001original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,...,NaN,wild,non_PA,NaN,border,D1.1,NaN,wild,wild,other
12688,12688,12688,a/vulture/md/25001987003original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,...,NaN,wild,non_PA,NaN,border,D1.1,NaN,wild,wild,other
12698,12698,12698,A/chicken/Pennsylvania/c_com2/2025,2025-03-16,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,Lebanon,domestic,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
12701,12701,12701,A/chicken/Pennsylvania/c_com5/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,unknown,domestic,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA
12702,12702,12702,A/chicken/Pennsylvania/c_com6/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,...,unknown,domestic,Pennsylvania,NaN,PA,D1.1,PA,PA_domestic,PA_domestic,PA

In [40]:
filtered_df['state_domstat'].value_counts()

state_domstat
wild           84
PA_domestic    51
NY_domestic    45
other          35
Name: count, dtype: int64

In [42]:
filtered_df['state_domstat']=filtered_df['state_domstat'].str.replace("other", "domestic")

filtered_df['state_domstat'].value_counts()

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_52138/4241420994.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['state_domstat']=filtered_df['state_domstat'].str.replace("other", "domestic")

state_domstat
wild           84
PA_domestic    51
NY_domestic    45
domestic       35
Name: count, dtype: int64

In [45]:
filtered_df['pa_ny_nj_other'].value_counts()

pa_ny_nj_other
PA       79
NY       78
other    46
NJ       12
Name: count, dtype: int64

In [46]:
filtered_df['wild_dom_lbm'].value_counts()

wild_dom_lbm
domestic    114
wild         84
lbm          17
Name: count, dtype: int64

In [43]:
##filter fasta to just the strains with known dom-stat
allowed_strains = set(filtered_df['strain'].astype(str))

# 2. Filter and Modify
input_fasta = "aligned_314.fasta"
output_fasta = "aligned_215.fasta"

with open(output_fasta, "w") as output_handle:
    for record in SeqIO.parse(input_fasta, "fasta"):
        # Match against ID or description
        if record.id in allowed_strains:            
            # Write the record
            SeqIO.write(record, output_handle, "fasta")

In [44]:
# Create a dictionary for quick lookup of metadata by subtree_name for statesgrouped2 and nynypaother
metadata_dict = filtered_df.set_index('strain').to_dict(orient='index')

# Process all subtree alignment files in a folder
input_files = glob.glob('aligned_215.fasta')  # Adjust path as needed

for fasta_file in input_files:
    output_file = fasta_file.replace(".fasta", "_w_meta215.fasta")
    
    with open(fasta_file, 'r') as input_handle, open(output_file, 'w') as output_handle:
        for record in SeqIO.parse(input_handle, 'fasta'):
            # Find the corresponding metadata (default to 'unknown' if not found)
            metadata = metadata_dict.get(record.id, {'date': 'unknown', 
                                        'wild_dom_lbm': 'unknown', 
                                        'state_domstat':'unknown',
                                        'pa_ny_nj_other': 'unknown',
                                        'order': 'unknown'})
            # Update the header with all metadata fields
            record.id = f"{record.id}|{metadata['date']}|{metadata['wild_dom_lbm']}|{metadata['state_domstat']}|{metadata['pa_ny_nj_other']}|{metadata['order']}|"
            record.description = ""  # Clear description to avoid duplicating info
            
            # Write the modified record to the output file
            SeqIO.write(record, output_handle, 'fasta')
    
    print(f"Modified FASTA file saved to {output_file}")

Modified FASTA file saved to aligned_215_w_meta215.fasta