In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../phylo/2025_data_tomerge/NCBI-BVBRC_FINAL_ha.tsv', sep='\t')
df.head()

,Unnamed: 0,genbank_acc,bp_length,ncbibvbrc_segment,ncbibvbrc_nonambigdate,ncbibvbrc_date,ncbibvbrc_strain,ncbibvbrc_division,ncbibvbrc_strain_host,ncbibvbrc_order,...,ncbibvbrc_hostgroup,ncbibvbrc_country,ncbibvbrc_subtype,bvbrc_assembled,strain_segment_updated,strain,year_only,month_only,source,Genome ID
0,3,OQ957612.1,1704.0,4.0,2022-02-06,2022-02-06,a/americanblackduck/connecticut/22005000001/2022,connecticut,americanblackduck,anseriformes,...,duck,USA,H5N1,no,a/americanblackduck/connecticut/22005000001/20...,a/americanblackduck/connecticut/22005000001/20...,2022,2,ncbibvbrc,11320.455519
1,11,OQ957620.1,1704.0,4.0,2022-02-16,2022-02-16,a/americanblackduck/connecticut/22005313006/2022,connecticut,americanblackduck,anseriformes,...,duck,USA,H5N1,no,a/americanblackduck/connecticut/22005313006/20...,a/americanblackduck/connecticut/22005313006/20...,2022,2,ncbibvbrc,11320.455526
2,19,OQ957628.1,1704.0,4.0,2022-02-16,2022-02-16,a/americanblackduck/connecticut/22005313007/2022,connecticut,americanblackduck,anseriformes,...,duck,USA,H5N1,no,a/americanblackduck/connecticut/22005313007/20...,a/americanblackduck/connecticut/22005313007/20...,2022,2,ncbibvbrc,11320.455535
3,27,OQ957636.1,1704.0,4.0,2022-02-16,2022-02-16,a/americanblackduck/connecticut/22005313008/2022,connecticut,americanblackduck,anseriformes,...,duck,USA,H5N1,no,a/americanblackduck/connecticut/22005313008/20...,a/americanblackduck/connecticut/22005313008/20...,2022,2,ncbibvbrc,11320.455544
4,35,PQ701321.1,1704.0,4.0,2022-10-31,2022-10-31,a/americanblackduck/ma/23001397010original/2022,massachusetts,americanblackduck,anseriformes,...,duck,USA,H5N1,no,a/americanblackduck/massachusetts/23001397010/...,a/americanblackduck/ma/23001397010original/202...,2022,10,ncbibvbrc,11320.718253

In [3]:
df.columns

Index(['Unnamed: 0', 'genbank_acc', 'bp_length', 'ncbibvbrc_segment',
       'ncbibvbrc_nonambigdate', 'ncbibvbrc_date', 'ncbibvbrc_strain',
       'ncbibvbrc_division', 'ncbibvbrc_strain_host', 'ncbibvbrc_order',
       'ncbibvbrc_domesticstatus', 'ncbibvbrc_corrected_host',
       'ncbibvbrc_flyway', 'ncbibvbrc_statecoord', 'ncbibvbrc_hostgroup',
       'ncbibvbrc_country', 'ncbibvbrc_subtype', 'bvbrc_assembled',
       'strain_segment_updated', 'strain', 'year_only', 'month_only', 'source',
       'Genome ID'],
      dtype='object')

In [4]:
df['year_only'].value_counts()

year_only
2022    5706
2024    1228
2023    1112
2025     865
2021      25
Name: count, dtype: int64

In [5]:
df25 = df[df['year_only'] == 2025]
df25.head()

,Unnamed: 0,genbank_acc,bp_length,ncbibvbrc_segment,ncbibvbrc_nonambigdate,ncbibvbrc_date,ncbibvbrc_strain,ncbibvbrc_division,ncbibvbrc_strain_host,ncbibvbrc_order,...,ncbibvbrc_hostgroup,ncbibvbrc_country,ncbibvbrc_subtype,bvbrc_assembled,strain_segment_updated,strain,year_only,month_only,source,Genome ID
62,499,PV336228.1,1704.0,4.0,2025-01-16,2025-01-16,a/americancrow/ia/25002028001original/2025,iowa,americancrow,passeriformes,...,songbird-etc,USA,H5N1,no,a/americancrow/iowa/25002028001/2025_4,a/americancrow/ia/25002028001original/2025|202...,2025,1,ncbi,NaN
173,1387,PV336236.1,1704.0,4.0,2025-01-13,2025-01-13,a/americancrow/pa/25002235001original/2025,pennsylvania,americancrow,passeriformes,...,songbird-etc,USA,H5N1,no,a/americancrow/pennsylvania/25002235001/2025_4,a/americancrow/pa/25002235001original/2025|202...,2025,1,ncbi,NaN
174,1395,PV336244.1,1704.0,4.0,2025-01-13,2025-01-13,a/americancrow/pa/25002235002original/2025,pennsylvania,americancrow,passeriformes,...,songbird-etc,USA,H5N1,no,a/americancrow/pennsylvania/25002235002/2025_4,a/americancrow/pa/25002235002original/2025|202...,2025,1,ncbi,NaN
402,3219,PV336252.1,1704.0,4.0,2025-01-04,2025-01-04,a/americanwigeon/az/25001910001original/2025,arizona,americanwigeon,anseriformes,...,duck,USA,H5N1,no,a/americanwigeon/arizona/25001910001/2025_4,a/americanwigeon/az/25001910001original/2025|2...,2025,1,ncbi,NaN
474,3803,PV336213.1,1704.0,4.0,2025-01-13,2025-01-13,a/americanwoodcock/ar/25003125001original/2025,arkansas,americanwoodcock,charadriiformes,...,shorebird,USA,H5N1,no,a/americanwoodcock/arkansas/25003125001/2025_4,a/americanwoodcock/ar/25003125001original/2025...,2025,1,ncbi,NaN

In [6]:
df25.drop(columns=['Unnamed: 0', 'genbank_acc', 'bp_length', 'ncbibvbrc_segment',
       'ncbibvbrc_nonambigdate', 'ncbibvbrc_statecoord', 'bvbrc_assembled','source',
       'Genome ID','strain_segment_updated', 'month_only', 'ncbibvbrc_hostgroup'], inplace=True)
df25

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_3780/59778850.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df25.drop(columns=['Unnamed: 0', 'genbank_acc', 'bp_length', 'ncbibvbrc_segment',

,ncbibvbrc_date,ncbibvbrc_strain,ncbibvbrc_division,ncbibvbrc_strain_host,ncbibvbrc_order,ncbibvbrc_domesticstatus,ncbibvbrc_corrected_host,ncbibvbrc_flyway,ncbibvbrc_country,ncbibvbrc_subtype,strain,year_only
62,2025-01-16,a/americancrow/ia/25002028001original/2025,iowa,americancrow,passeriformes,wild,americancrow,MississippiFlyway,USA,H5N1,a/americancrow/ia/25002028001original/2025|202...,2025
173,2025-01-13,a/americancrow/pa/25002235001original/2025,pennsylvania,americancrow,passeriformes,wild,americancrow,AtlanticFlyway,USA,H5N1,a/americancrow/pa/25002235001original/2025|202...,2025
174,2025-01-13,a/americancrow/pa/25002235002original/2025,pennsylvania,americancrow,passeriformes,wild,americancrow,AtlanticFlyway,USA,H5N1,a/americancrow/pa/25002235002original/2025|202...,2025
402,2025-01-04,a/americanwigeon/az/25001910001original/2025,arizona,americanwigeon,anseriformes,wild,americanwigeon,PacificFlyway,USA,H5N1,a/americanwigeon/az/25001910001original/2025|2...,2025
474,2025-01-13,a/americanwoodcock/ar/25003125001original/2025,arkansas,americanwoodcock,charadriiformes,wild,americanwoodcock,MississippiFlyway,USA,H5N1,a/americanwoodcock/ar/25003125001original/2025...,2025
...,...,...,...,...,...,...,...,...,...,...,...,...
8769,2025-01-15,a/vulture/md/25001987003original/2025,maryland,vulture,accipitriformes,wild,vulture,AtlanticFlyway,USA,H5N1,a/vulture/md/25001987003original/2025|2025-01-...,2025
8809,2025-01-17,a/westerngull/ca/25003273005original/2025,california,westerngull,charadriiformes,wild,westerngull,PacificFlyway,USA,H5N1,a/westerngull/ca/25003273005original/2025|2025...,2025
8810,2025-01-17,a/westerngull/ca/25003273006original/2025,california,westerngull,charadriiformes,wild,westerngull,PacificFlyway,USA,H5N1,a/westerngull/ca/25003273006original/2025|2025...,2025
8864,2025-01-17,a/woodduck/ky/25002824002original/2025,kentucky,woodduck,anseriformes,wild,woodduck,MississippiFlyway,USA,H5N1,a/woodduck/ky/25002824002original/2025|2025-01...,2025
8894,2025-01-15,a/woodduck/ms/25002206001original/2025,mississippi,woodduck,anseriformes,wild,woodduck,MississippiFlyway,USA,H5N1,a/woodduck/ms/25002206001original/2025|2025-01...,2025

In [7]:
df25.rename(columns={"strain": "strain_long", "ncbibvbrc_domesticstatus": "domestic_status"}, inplace=True)

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_3780/400407169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df25.rename(columns={"strain": "strain_long", "ncbibvbrc_domesticstatus": "domestic_status"}, inplace=True)

In [8]:
df25.columns = df25.columns.str.replace('ncbibvbrc_', '')
df25

,date,strain,division,strain_host,order,domestic_status,corrected_host,flyway,country,subtype,strain_long,year_only
62,2025-01-16,a/americancrow/ia/25002028001original/2025,iowa,americancrow,passeriformes,wild,americancrow,MississippiFlyway,USA,H5N1,a/americancrow/ia/25002028001original/2025|202...,2025
173,2025-01-13,a/americancrow/pa/25002235001original/2025,pennsylvania,americancrow,passeriformes,wild,americancrow,AtlanticFlyway,USA,H5N1,a/americancrow/pa/25002235001original/2025|202...,2025
174,2025-01-13,a/americancrow/pa/25002235002original/2025,pennsylvania,americancrow,passeriformes,wild,americancrow,AtlanticFlyway,USA,H5N1,a/americancrow/pa/25002235002original/2025|202...,2025
402,2025-01-04,a/americanwigeon/az/25001910001original/2025,arizona,americanwigeon,anseriformes,wild,americanwigeon,PacificFlyway,USA,H5N1,a/americanwigeon/az/25001910001original/2025|2...,2025
474,2025-01-13,a/americanwoodcock/ar/25003125001original/2025,arkansas,americanwoodcock,charadriiformes,wild,americanwoodcock,MississippiFlyway,USA,H5N1,a/americanwoodcock/ar/25003125001original/2025...,2025
...,...,...,...,...,...,...,...,...,...,...,...,...
8769,2025-01-15,a/vulture/md/25001987003original/2025,maryland,vulture,accipitriformes,wild,vulture,AtlanticFlyway,USA,H5N1,a/vulture/md/25001987003original/2025|2025-01-...,2025
8809,2025-01-17,a/westerngull/ca/25003273005original/2025,california,westerngull,charadriiformes,wild,westerngull,PacificFlyway,USA,H5N1,a/westerngull/ca/25003273005original/2025|2025...,2025
8810,2025-01-17,a/westerngull/ca/25003273006original/2025,california,westerngull,charadriiformes,wild,westerngull,PacificFlyway,USA,H5N1,a/westerngull/ca/25003273006original/2025|2025...,2025
8864,2025-01-17,a/woodduck/ky/25002824002original/2025,kentucky,woodduck,anseriformes,wild,woodduck,MississippiFlyway,USA,H5N1,a/woodduck/ky/25002824002original/2025|2025-01...,2025
8894,2025-01-15,a/woodduck/ms/25002206001original/2025,mississippi,woodduck,anseriformes,wild,woodduck,MississippiFlyway,USA,H5N1,a/woodduck/ms/25002206001original/2025|2025-01...,2025

In [9]:
df25.division = df25.division.str.title()
df25.country = df25.country.str.title()
df25['flyway'] = df25['flyway'].str.replace('Fly', ' Fly', regex=False).str.strip()
df25['host'] = 'Avian'
df25['region'] = 'North America'

df25.subtype = df25.subtype.str.lower()


df25

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_3780/1010844791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df25.division = df25.division.str.title()
/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_3780/1010844791.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df25.country = df25.country.str.title()
/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_3780/1010844791.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df25['flyway'] = df25['flyway'].str.replace('Fly', ' Fly', regex=False).str.strip()
/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_3780/1010844791.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df25['host'] = 'Avian'
/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_3780/1010844791.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df25['region'] = 'North America'
/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_3780/1010844791.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df25.subtype = df25.subtype.str.lower()

,date,strain,division,strain_host,order,domestic_status,corrected_host,flyway,country,subtype,strain_long,year_only,host,region
62,2025-01-16,a/americancrow/ia/25002028001original/2025,Iowa,americancrow,passeriformes,wild,americancrow,Mississippi Flyway,Usa,h5n1,a/americancrow/ia/25002028001original/2025|202...,2025,Avian,North America
173,2025-01-13,a/americancrow/pa/25002235001original/2025,Pennsylvania,americancrow,passeriformes,wild,americancrow,Atlantic Flyway,Usa,h5n1,a/americancrow/pa/25002235001original/2025|202...,2025,Avian,North America
174,2025-01-13,a/americancrow/pa/25002235002original/2025,Pennsylvania,americancrow,passeriformes,wild,americancrow,Atlantic Flyway,Usa,h5n1,a/americancrow/pa/25002235002original/2025|202...,2025,Avian,North America
402,2025-01-04,a/americanwigeon/az/25001910001original/2025,Arizona,americanwigeon,anseriformes,wild,americanwigeon,Pacific Flyway,Usa,h5n1,a/americanwigeon/az/25001910001original/2025|2...,2025,Avian,North America
474,2025-01-13,a/americanwoodcock/ar/25003125001original/2025,Arkansas,americanwoodcock,charadriiformes,wild,americanwoodcock,Mississippi Flyway,Usa,h5n1,a/americanwoodcock/ar/25003125001original/2025...,2025,Avian,North America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8769,2025-01-15,a/vulture/md/25001987003original/2025,Maryland,vulture,accipitriformes,wild,vulture,Atlantic Flyway,Usa,h5n1,a/vulture/md/25001987003original/2025|2025-01-...,2025,Avian,North America
8809,2025-01-17,a/westerngull/ca/25003273005original/2025,California,westerngull,charadriiformes,wild,westerngull,Pacific Flyway,Usa,h5n1,a/westerngull/ca/25003273005original/2025|2025...,2025,Avian,North America
8810,2025-01-17,a/westerngull/ca/25003273006original/2025,California,westerngull,charadriiformes,wild,westerngull,Pacific Flyway,Usa,h5n1,a/westerngull/ca/25003273006original/2025|2025...,2025,Avian,North America
8864,2025-01-17,a/woodduck/ky/25002824002original/2025,Kentucky,woodduck,anseriformes,wild,woodduck,Mississippi Flyway,Usa,h5n1,a/woodduck/ky/25002824002original/2025|2025-01...,2025,Avian,North America
8894,2025-01-15,a/woodduck/ms/25002206001original/2025,Mississippi,woodduck,anseriformes,wild,woodduck,Mississippi Flyway,Usa,h5n1,a/woodduck/ms/25002206001original/2025|2025-01...,2025,Avian,North America

In [11]:
##i confirmed via nextclade that these are all 2344b, so will input there for h5_labelclade for all columns
df25['h5_label_clade'] = '2.3.4.4b'
df25

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_3780/3054246836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df25['h5_label_clade'] = '2.3.4.4b'

,date,strain,division,strain_host,order,domestic_status,corrected_host,flyway,country,subtype,strain_long,year_only,host,region,h5_label_clade
62,2025-01-16,a/americancrow/ia/25002028001original/2025,Iowa,americancrow,passeriformes,wild,americancrow,Mississippi Flyway,Usa,h5n1,a/americancrow/ia/25002028001original/2025|202...,2025,Avian,North America,2.3.4.4b
173,2025-01-13,a/americancrow/pa/25002235001original/2025,Pennsylvania,americancrow,passeriformes,wild,americancrow,Atlantic Flyway,Usa,h5n1,a/americancrow/pa/25002235001original/2025|202...,2025,Avian,North America,2.3.4.4b
174,2025-01-13,a/americancrow/pa/25002235002original/2025,Pennsylvania,americancrow,passeriformes,wild,americancrow,Atlantic Flyway,Usa,h5n1,a/americancrow/pa/25002235002original/2025|202...,2025,Avian,North America,2.3.4.4b
402,2025-01-04,a/americanwigeon/az/25001910001original/2025,Arizona,americanwigeon,anseriformes,wild,americanwigeon,Pacific Flyway,Usa,h5n1,a/americanwigeon/az/25001910001original/2025|2...,2025,Avian,North America,2.3.4.4b
474,2025-01-13,a/americanwoodcock/ar/25003125001original/2025,Arkansas,americanwoodcock,charadriiformes,wild,americanwoodcock,Mississippi Flyway,Usa,h5n1,a/americanwoodcock/ar/25003125001original/2025...,2025,Avian,North America,2.3.4.4b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8769,2025-01-15,a/vulture/md/25001987003original/2025,Maryland,vulture,accipitriformes,wild,vulture,Atlantic Flyway,Usa,h5n1,a/vulture/md/25001987003original/2025|2025-01-...,2025,Avian,North America,2.3.4.4b
8809,2025-01-17,a/westerngull/ca/25003273005original/2025,California,westerngull,charadriiformes,wild,westerngull,Pacific Flyway,Usa,h5n1,a/westerngull/ca/25003273005original/2025|2025...,2025,Avian,North America,2.3.4.4b
8810,2025-01-17,a/westerngull/ca/25003273006original/2025,California,westerngull,charadriiformes,wild,westerngull,Pacific Flyway,Usa,h5n1,a/westerngull/ca/25003273006original/2025|2025...,2025,Avian,North America,2.3.4.4b
8864,2025-01-17,a/woodduck/ky/25002824002original/2025,Kentucky,woodduck,anseriformes,wild,woodduck,Mississippi Flyway,Usa,h5n1,a/woodduck/ky/25002824002original/2025|2025-01...,2025,Avian,North America,2.3.4.4b
8894,2025-01-15,a/woodduck/ms/25002206001original/2025,Mississippi,woodduck,anseriformes,wild,woodduck,Mississippi Flyway,Usa,h5n1,a/woodduck/ms/25002206001original/2025|2025-01...,2025,Avian,North America,2.3.4.4b

In [10]:
df25.columns

Index(['date', 'strain', 'division', 'strain_host', 'order', 'domestic_status',
       'corrected_host', 'flyway', 'country', 'subtype', 'strain_long',
       'year_only', 'host', 'region'],
      dtype='object')

In [61]:
# new_order = ["strain", "date", "region", "division", "host", "subtype", "order", "flyway"]
# df25 = df25[new_order]
# df25

,strain,date,region,division,host,subtype,order,flyway
62,a/americancrow/ia/25002028001original/2025,2025-01-16,North America,Iowa,Avian,h5n1,passeriformes,Mississippi Flyway
173,a/americancrow/pa/25002235001original/2025,2025-01-13,North America,Pennsylvania,Avian,h5n1,passeriformes,Atlantic Flyway
174,a/americancrow/pa/25002235002original/2025,2025-01-13,North America,Pennsylvania,Avian,h5n1,passeriformes,Atlantic Flyway
402,a/americanwigeon/az/25001910001original/2025,2025-01-04,North America,Arizona,Avian,h5n1,anseriformes,Pacific Flyway
474,a/americanwoodcock/ar/25003125001original/2025,2025-01-13,North America,Arkansas,Avian,h5n1,charadriiformes,Mississippi Flyway
...,...,...,...,...,...,...,...,...
8769,a/vulture/md/25001987003original/2025,2025-01-15,North America,Maryland,Avian,h5n1,accipitriformes,Atlantic Flyway
8809,a/westerngull/ca/25003273005original/2025,2025-01-17,North America,California,Avian,h5n1,charadriiformes,Pacific Flyway
8810,a/westerngull/ca/25003273006original/2025,2025-01-17,North America,California,Avian,h5n1,charadriiformes,Pacific Flyway
8864,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Kentucky,Avian,h5n1,anseriformes,Mississippi Flyway
8894,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Mississippi,Avian,h5n1,anseriformes,Mississippi Flyway

In [67]:
##now i want to filter the fastas to only be the 2025 ones in this list
##and also rename the fasta headers to just strain not strain long:
from Bio import SeqIO
from pathlib import Path

# Create lookup: name -> strain
name_to_strain = dict(zip(df25["strain_long"], df25["strain"]))
valid_names = set(df25["strain_long"])

fasta_dir = Path("../phylo/2025_data_tomerge")        # input folder
out_dir = Path("../phylo/2025_data_tomerge/filtered_fastas") # output folder
out_dir.mkdir(exist_ok=True)

for fasta_file in fasta_dir.glob("*.fasta"):
    out_records = []

    for rec in SeqIO.parse(fasta_file, "fasta"):
        header = rec.id  # assumes header starts with name

        if header in valid_names:
            rec.id = name_to_strain[header]
            rec.description = ""  # avoid old header text
            out_records.append(rec)

    SeqIO.write(out_records, out_dir / fasta_file.name, "fasta")

In [12]:
df25.to_csv('../phylo/2025_data_tomerge/filtered_fastas/cleaned_2025_meta.tsv', sep = '\t', index=False)

In [70]:
df25.info()

<class 'pandas.core.frame.DataFrame'>
Index: 865 entries, 62 to 8894
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             865 non-null    object
 1   strain           865 non-null    object
 2   division         865 non-null    object
 3   strain_host      865 non-null    object
 4   order            865 non-null    object
 5   domestic_status  865 non-null    object
 6   corrected_host   865 non-null    object
 7   flyway           865 non-null    object
 8   country          865 non-null    object
 9   subtype          865 non-null    object
 10  strain_long      865 non-null    object
 11  year_only        865 non-null    int64
 12  host             865 non-null    object
 13  region           865 non-null    object
dtypes: int64(1), object(13)
memory usage: 101.4+ KB

In [13]:
data = pd.read_csv('../phylo/2026-01-27_fullgenome_PAtree/data/2026_01_27_meta_merged_northam_PA_fornextstrain.tsv', sep='\t')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11828 entries, 0 to 11827
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   strain           11828 non-null  object
 1   date             11828 non-null  object
 2   region           11828 non-null  object
 3   country          11828 non-null  object
 4   division         11828 non-null  object
 5   location         11828 non-null  object
 6   host             11828 non-null  object
 7   subtype          11828 non-null  object
 8   originating_lab  11828 non-null  object
 9   submitting_lab   11828 non-null  object
 10  h5_label_clade   11828 non-null  object
 11  animal           11828 non-null  object
 12  order            11485 non-null  object
 13  flyway           9312 non-null   object
 14  geo_region_na    9312 non-null   object
 15  id               11828 non-null  object
 16  species          2493 non-null   object
 17  domestic_status  7310 non-null   object
 18  species_group    11828 non-null  object
 19  county           68 non-null     object
 20  PA_status        11828 non-null  object
dtypes: object(21)
memory usage: 1.9+ MB

In [14]:
merge = pd.concat([data, df25], ignore_index=True)
merge

,strain,date,region,country,division,location,host,subtype,originating_lab,submitting_lab,...,id,species,domestic_status,species_group,county,PA_status,strain_host,corrected_host,strain_long,year_only
0,A/TrumpeterSwan/BritishColumbia/AIVPHL775/2022,2022-11-28,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,Public Health Agency Of Canada,...,AIVPHL775,NaN,wild,Anseriformes,NaN,non-PA,NaN,NaN,NaN,NaN
1,A/Americanwigeon/NorthCarolina/AH0182517/2022,2022-01-08,North America,Usa,North Carolina,North Carolina,Avian,h5n1,Usda Nwrc Wildlife Services,National Veterinary Services Laboratories Usda,...,AH0182517,American wigeon,wild,Anseriformes,NaN,non-PA,NaN,NaN,NaN,NaN
2,A/turkey/BritishColumbia/AIVPHL128/2022,2022-05-18,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,British Columbia Centre For Disease Control,...,AIVPHL128,turkey,Unknown,Galliformes,NaN,non-PA,NaN,NaN,NaN,NaN
3,A/turkey/Minnesota/USDA011789003/2022,2022-04-17,North America,Usa,Minnesota,Minnesota,Avian,h5n1,?,?,...,USDA011789003,turkey,Unknown,Galliformes,NaN,non-PA,NaN,NaN,NaN,NaN
4,A/BlackVulture/Florida/USDA012636001/2022,2022-04-22,North America,Usa,Florida,Florida,Avian,h5n1,?,?,...,USDA012636001,Black Vulture,wild,Raptor,NaN,non-PA,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12688,a/vulture/md/25001987003original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,wild,NaN,NaN,NaN,vulture,vulture,a/vulture/md/25001987003original/2025|2025-01-...,2025.0
12689,a/westerngull/ca/25003273005original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,wild,NaN,NaN,NaN,westerngull,westerngull,a/westerngull/ca/25003273005original/2025|2025...,2025.0
12690,a/westerngull/ca/25003273006original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,wild,NaN,NaN,NaN,westerngull,westerngull,a/westerngull/ca/25003273006original/2025|2025...,2025.0
12691,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Usa,Kentucky,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,wild,NaN,NaN,NaN,woodduck,woodduck,a/woodduck/ky/25002824002original/2025|2025-01...,2025.0
12692,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Usa,Mississippi,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,wild,NaN,NaN,NaN,woodduck,woodduck,a/woodduck/ms/25002206001original/2025|2025-01...,2025.0

In [15]:
merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12693 entries, 0 to 12692
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   strain           12693 non-null  object
 1   date             12693 non-null  object
 2   region           12693 non-null  object
 3   country          12693 non-null  object
 4   division         12693 non-null  object
 5   location         11828 non-null  object
 6   host             12693 non-null  object
 7   subtype          12693 non-null  object
 8   originating_lab  11828 non-null  object
 9   submitting_lab   11828 non-null  object
 10  h5_label_clade   12693 non-null  object
 11  animal           11828 non-null  object
 12  order            12350 non-null  object
 13  flyway           10177 non-null  object
 14  geo_region_na    9312 non-null   object
 15  id               11828 non-null  object
 16  species          2493 non-null   object
 17  domestic_status  8175 non-null   object
 18  species_group    11828 non-null  object
 19  county           68 non-null     object
 20  PA_status        11828 non-null  object
 21  strain_host      865 non-null    object
 22  corrected_host   865 non-null    object
 23  strain_long      865 non-null    object
 24  year_only        865 non-null    float64
dtypes: float64(1), object(24)
memory usage: 2.4+ MB

In [80]:
merge.columns

Index(['strain', 'date', 'region', 'country', 'division', 'location', 'host',
       'subtype', 'originating_lab', 'submitting_lab', 'h5_label_clade',
       'animal', 'order', 'flyway', 'geo_region_na', 'id', 'species',
       'domestic_status', 'species_group', 'county', 'PA_status',
       'strain_host', 'corrected_host', 'strain_long', 'year_only'],
      dtype='object')

In [16]:
merge['PA_status'] = merge['division'].apply(lambda x: 'Pennsylvania' if x == 'Pennsylvania' else 'non_PA')

In [17]:
merge["species"] = merge["species"].fillna(merge["strain_host"])
merge

,strain,date,region,country,division,location,host,subtype,originating_lab,submitting_lab,...,id,species,domestic_status,species_group,county,PA_status,strain_host,corrected_host,strain_long,year_only
0,A/TrumpeterSwan/BritishColumbia/AIVPHL775/2022,2022-11-28,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,Public Health Agency Of Canada,...,AIVPHL775,NaN,wild,Anseriformes,NaN,non_PA,NaN,NaN,NaN,NaN
1,A/Americanwigeon/NorthCarolina/AH0182517/2022,2022-01-08,North America,Usa,North Carolina,North Carolina,Avian,h5n1,Usda Nwrc Wildlife Services,National Veterinary Services Laboratories Usda,...,AH0182517,American wigeon,wild,Anseriformes,NaN,non_PA,NaN,NaN,NaN,NaN
2,A/turkey/BritishColumbia/AIVPHL128/2022,2022-05-18,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,British Columbia Centre For Disease Control,...,AIVPHL128,turkey,Unknown,Galliformes,NaN,non_PA,NaN,NaN,NaN,NaN
3,A/turkey/Minnesota/USDA011789003/2022,2022-04-17,North America,Usa,Minnesota,Minnesota,Avian,h5n1,?,?,...,USDA011789003,turkey,Unknown,Galliformes,NaN,non_PA,NaN,NaN,NaN,NaN
4,A/BlackVulture/Florida/USDA012636001/2022,2022-04-22,North America,Usa,Florida,Florida,Avian,h5n1,?,?,...,USDA012636001,Black Vulture,wild,Raptor,NaN,non_PA,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12688,a/vulture/md/25001987003original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,NaN,NaN,...,NaN,vulture,wild,NaN,NaN,non_PA,vulture,vulture,a/vulture/md/25001987003original/2025|2025-01-...,2025.0
12689,a/westerngull/ca/25003273005original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,westerngull,wild,NaN,NaN,non_PA,westerngull,westerngull,a/westerngull/ca/25003273005original/2025|2025...,2025.0
12690,a/westerngull/ca/25003273006original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,westerngull,wild,NaN,NaN,non_PA,westerngull,westerngull,a/westerngull/ca/25003273006original/2025|2025...,2025.0
12691,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Usa,Kentucky,NaN,Avian,h5n1,NaN,NaN,...,NaN,woodduck,wild,NaN,NaN,non_PA,woodduck,woodduck,a/woodduck/ky/25002824002original/2025|2025-01...,2025.0
12692,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Usa,Mississippi,NaN,Avian,h5n1,NaN,NaN,...,NaN,woodduck,wild,NaN,NaN,non_PA,woodduck,woodduck,a/woodduck/ms/25002206001original/2025|2025-01...,2025.0

In [18]:
merge.drop(columns=['strain_host', 'corrected_host', 'strain_long', 'year_only'], inplace=True)
merge

,strain,date,region,country,division,location,host,subtype,originating_lab,submitting_lab,...,animal,order,flyway,geo_region_na,id,species,domestic_status,species_group,county,PA_status
0,A/TrumpeterSwan/BritishColumbia/AIVPHL775/2022,2022-11-28,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,Public Health Agency Of Canada,...,trumpeterswan,anseriformes,Pacific Flyway,Canada,AIVPHL775,NaN,wild,Anseriformes,NaN,non_PA
1,A/Americanwigeon/NorthCarolina/AH0182517/2022,2022-01-08,North America,Usa,North Carolina,North Carolina,Avian,h5n1,Usda Nwrc Wildlife Services,National Veterinary Services Laboratories Usda,...,americanwigeon,anseriformes,Atlantic Flyway,South,AH0182517,American wigeon,wild,Anseriformes,NaN,non_PA
2,A/turkey/BritishColumbia/AIVPHL128/2022,2022-05-18,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,British Columbia Centre For Disease Control,...,turkey,galliformes,Pacific Flyway,Canada,AIVPHL128,turkey,Unknown,Galliformes,NaN,non_PA
3,A/turkey/Minnesota/USDA011789003/2022,2022-04-17,North America,Usa,Minnesota,Minnesota,Avian,h5n1,?,?,...,turkey,galliformes,Mississippi Flyway,Midwest,USDA011789003,turkey,Unknown,Galliformes,NaN,non_PA
4,A/BlackVulture/Florida/USDA012636001/2022,2022-04-22,North America,Usa,Florida,Florida,Avian,h5n1,?,?,...,blackvulture,accipitriformes,Atlantic Flyway,South,USDA012636001,Black Vulture,wild,Raptor,NaN,non_PA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12688,a/vulture/md/25001987003original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,NaN,NaN,...,NaN,accipitriformes,Atlantic Flyway,NaN,NaN,vulture,wild,NaN,NaN,non_PA
12689,a/westerngull/ca/25003273005original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,charadriiformes,Pacific Flyway,NaN,NaN,westerngull,wild,NaN,NaN,non_PA
12690,a/westerngull/ca/25003273006original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,charadriiformes,Pacific Flyway,NaN,NaN,westerngull,wild,NaN,NaN,non_PA
12691,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Usa,Kentucky,NaN,Avian,h5n1,NaN,NaN,...,NaN,anseriformes,Mississippi Flyway,NaN,NaN,woodduck,wild,NaN,NaN,non_PA
12692,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Usa,Mississippi,NaN,Avian,h5n1,NaN,NaN,...,NaN,anseriformes,Mississippi Flyway,NaN,NaN,woodduck,wild,NaN,NaN,non_PA

In [19]:
merge.drop_duplicates(subset=['strain', 'date'], keep='first')
merge
##doesnt seem like there are any dupes in the 2025 data...which kinda tracks because i have very little if any presently?

,strain,date,region,country,division,location,host,subtype,originating_lab,submitting_lab,...,animal,order,flyway,geo_region_na,id,species,domestic_status,species_group,county,PA_status
0,A/TrumpeterSwan/BritishColumbia/AIVPHL775/2022,2022-11-28,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,Public Health Agency Of Canada,...,trumpeterswan,anseriformes,Pacific Flyway,Canada,AIVPHL775,NaN,wild,Anseriformes,NaN,non_PA
1,A/Americanwigeon/NorthCarolina/AH0182517/2022,2022-01-08,North America,Usa,North Carolina,North Carolina,Avian,h5n1,Usda Nwrc Wildlife Services,National Veterinary Services Laboratories Usda,...,americanwigeon,anseriformes,Atlantic Flyway,South,AH0182517,American wigeon,wild,Anseriformes,NaN,non_PA
2,A/turkey/BritishColumbia/AIVPHL128/2022,2022-05-18,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,British Columbia Centre For Disease Control,...,turkey,galliformes,Pacific Flyway,Canada,AIVPHL128,turkey,Unknown,Galliformes,NaN,non_PA
3,A/turkey/Minnesota/USDA011789003/2022,2022-04-17,North America,Usa,Minnesota,Minnesota,Avian,h5n1,?,?,...,turkey,galliformes,Mississippi Flyway,Midwest,USDA011789003,turkey,Unknown,Galliformes,NaN,non_PA
4,A/BlackVulture/Florida/USDA012636001/2022,2022-04-22,North America,Usa,Florida,Florida,Avian,h5n1,?,?,...,blackvulture,accipitriformes,Atlantic Flyway,South,USDA012636001,Black Vulture,wild,Raptor,NaN,non_PA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12688,a/vulture/md/25001987003original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,NaN,NaN,...,NaN,accipitriformes,Atlantic Flyway,NaN,NaN,vulture,wild,NaN,NaN,non_PA
12689,a/westerngull/ca/25003273005original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,charadriiformes,Pacific Flyway,NaN,NaN,westerngull,wild,NaN,NaN,non_PA
12690,a/westerngull/ca/25003273006original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,charadriiformes,Pacific Flyway,NaN,NaN,westerngull,wild,NaN,NaN,non_PA
12691,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Usa,Kentucky,NaN,Avian,h5n1,NaN,NaN,...,NaN,anseriformes,Mississippi Flyway,NaN,NaN,woodduck,wild,NaN,NaN,non_PA
12692,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Usa,Mississippi,NaN,Avian,h5n1,NaN,NaN,...,NaN,anseriformes,Mississippi Flyway,NaN,NaN,woodduck,wild,NaN,NaN,non_PA

In [21]:
merge.to_csv('../phylo/updated-merged-genefastas-northamPA/2026-02-24-northam-withPA-meta.tsv', sep='\t', index=False)

In [22]:
###now wanna add in new func annotations db stuff
import glob

files = glob.glob("../seq/analysis/functional_sites_2019_bygene/New Folder With Items/*.csv")

df = pd.concat((pd.read_csv(f) for f in files), ignore_index=True)

df.to_csv("combined.csv", index=False)

In [23]:
df

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes
0,1,4,-1.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN
1,2,4,5.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN
2,3,4,17.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,17.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN
4,5,4,17.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,62,8,69.0,NaN,NaN,H5N2,Wu et al. Virol. J. 2016,10.1186/s12985-016-0612-5,E,E69G,NaN,NaN,NaN,G,NaN,NaN
1245,63,8,75.0,NaN,NaN,NaN,Mänz et al. Nat. Commun. 2012,10.1038/ncomms1804,E,E75G,NaN,NaN,NaN,G,NaN,NaN
1246,64,8,88.0,NaN,NaN,H3N2,Ping et al. PLoS One 2011,10.1371/journal.pone.0021740,K,K88R,NaN,NaN,NaN,R,NaN,NaN
1247,65,8,110.0,NaN,NaN,H9N2,Sun et al. Sci. Adv. 2023,10.1126/sciadv.adg5175,G,G110E,NaN,NaN,NaN,E,NaN,NaN
1248,66,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN