In [14]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../../phylo/2026-03-13_largeNorthAm_withPA_updateddomstat/data/2026-03-13-northam-PA-meta-updateddomstat.tsv', sep='\t')
df

,strain,date,region,country,division,location,host,subtype,originating_lab,submitting_lab,...,geo_region_na,id,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state
0,A/TrumpeterSwan/BritishColumbia/AIVPHL775/2022,2022-11-28,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,Public Health Agency Of Canada,...,Canada,AIVPHL775,trumpeterswan,wild,Anseriformes,NaN,wild,non_PA,NaN,non-border
1,A/Americanwigeon/NorthCarolina/AH0182517/2022,2022-01-08,North America,Usa,North Carolina,North Carolina,Avian,h5n1,Usda Nwrc Wildlife Services,National Veterinary Services Laboratories Usda,...,South,AH0182517,American wigeon,wild,Anseriformes,NaN,wild,non_PA,wild,non-border
2,A/turkey/BritishColumbia/AIVPHL128/2022,2022-05-18,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,British Columbia Centre For Disease Control,...,Canada,AIVPHL128,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border
3,A/turkey/Minnesota/USDA011789003/2022,2022-04-17,North America,Usa,Minnesota,Minnesota,Avian,h5n1,?,?,...,Midwest,USDA011789003,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border
4,A/BlackVulture/Florida/USDA012636001/2022,2022-04-22,North America,Usa,Florida,Florida,Avian,h5n1,?,?,...,South,USDA012636001,Black Vulture,wild,Raptor,NaN,wild,non_PA,NaN,non-border
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12709,A/red_tailedhawk/Pennsylvania/rth_w4/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,rth_w4,red_tailed hawk,wild,NaN,Erie,wild,Pennsylvania,NaN,PA
12710,A/snowyowl/Pennsylvania/so_w1/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,so_w1,snowy owl,wild,NaN,Erie,wild,Pennsylvania,NaN,PA
12711,A/turkeyvulture/Pennsylvania/tv_w2/2025,2025-03-05,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,tv_w2,turkey vulture,wild,NaN,Erie,wild,Pennsylvania,NaN,PA
12712,A/turkeyvulture/Pennsylvania/tv_w3/2025,2025-03-24,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,tv_w3,turkey vulture,wild,NaN,Cumberland,wild,Pennsylvania,NaN,PA
12713,A/white_wingedscoter/Pennsylvania/wws_w1/2022,2022-12-19,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,wws_w1,white-winged scoter,wild,Anseriformes,Erie,wild,Pennsylvania,NaN,PA

In [3]:
gt = pd.read_csv('../../phylo/2026-03-13_largeNorthAm_withPA_updateddomstat/data/dedupe_seqkit/results/genotypes.tsv', sep='\t')
gt

,Strain,Genotype,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,a/americancrow/ia/25002028001original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
1,a/americancrow/pa/25002235001original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
2,a/americancrow/pa/25002235002original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
3,a/americanwigeon/az/25001910001original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
4,a/americanwoodcock/ar/25003125001original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
12074,A/chicken/Pennsylvania/c_com5/2025,D1.1,NaN,NaN,NaN,NaN,NaN
12075,A/chicken/Pennsylvania/c_com6/2025,D1.1,NaN,NaN,NaN,NaN,NaN
12076,A/chicken/Pennsylvania/c_lbm3/2025,D1.1,NaN,NaN,NaN,NaN,NaN
12077,A/duck/Pennsylvania/d_lbm2/2025,D1.1,NaN,NaN,NaN,NaN,NaN
12078,A/khakicampbell/Pennsylvania/kc_com7/2023,B3.3,NaN,NaN,NaN,NaN,NaN

In [5]:
gt.rename(columns={"Strain":"strain"}, inplace=True)
gt

,strain,Genotype,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,a/americancrow/ia/25002028001original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
1,a/americancrow/pa/25002235001original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
2,a/americancrow/pa/25002235002original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
3,a/americanwigeon/az/25001910001original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
4,a/americanwoodcock/ar/25003125001original/2025,D1.1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
12074,A/chicken/Pennsylvania/c_com5/2025,D1.1,NaN,NaN,NaN,NaN,NaN
12075,A/chicken/Pennsylvania/c_com6/2025,D1.1,NaN,NaN,NaN,NaN,NaN
12076,A/chicken/Pennsylvania/c_lbm3/2025,D1.1,NaN,NaN,NaN,NaN,NaN
12077,A/duck/Pennsylvania/d_lbm2/2025,D1.1,NaN,NaN,NaN,NaN,NaN
12078,A/khakicampbell/Pennsylvania/kc_com7/2023,B3.3,NaN,NaN,NaN,NaN,NaN

In [7]:
gt.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6'], inplace=True)

In [8]:
gt

                                               strain Genotype
0          a/americancrow/ia/25002028001original/2025     D1.1
1          a/americancrow/pa/25002235001original/2025     D1.1
2          a/americancrow/pa/25002235002original/2025     D1.1
3        a/americanwigeon/az/25001910001original/2025     D1.1
4      a/americanwoodcock/ar/25003125001original/2025     D1.1
...                                               ...      ...
12074              A/chicken/Pennsylvania/c_com5/2025     D1.1
12075              A/chicken/Pennsylvania/c_com6/2025     D1.1
12076              A/chicken/Pennsylvania/c_lbm3/2025     D1.1
12077                 A/duck/Pennsylvania/d_lbm2/2025     D1.1
12078       A/khakicampbell/Pennsylvania/kc_com7/2023     B3.3

[12079 rows x 2 columns]

In [9]:
# Merge df1 with the subset of df2 on the 'key' column
# 'how="left"' ensures all rows from df1 are included
merge = pd.merge(df, gt, on='strain', how='left')
merge

,strain,date,region,country,division,location,host,subtype,originating_lab,submitting_lab,...,id,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state,Genotype
0,A/TrumpeterSwan/BritishColumbia/AIVPHL775/2022,2022-11-28,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,Public Health Agency Of Canada,...,AIVPHL775,trumpeterswan,wild,Anseriformes,NaN,wild,non_PA,NaN,non-border,NaN
1,A/Americanwigeon/NorthCarolina/AH0182517/2022,2022-01-08,North America,Usa,North Carolina,North Carolina,Avian,h5n1,Usda Nwrc Wildlife Services,National Veterinary Services Laboratories Usda,...,AH0182517,American wigeon,wild,Anseriformes,NaN,wild,non_PA,wild,non-border,A1
2,A/turkey/BritishColumbia/AIVPHL128/2022,2022-05-18,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,British Columbia Centre For Disease Control,...,AIVPHL128,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border,B2.1
3,A/turkey/Minnesota/USDA011789003/2022,2022-04-17,North America,Usa,Minnesota,Minnesota,Avian,h5n1,?,?,...,USDA011789003,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border,B2.1
4,A/BlackVulture/Florida/USDA012636001/2022,2022-04-22,North America,Usa,Florida,Florida,Avian,h5n1,?,?,...,USDA012636001,Black Vulture,wild,Raptor,NaN,wild,non_PA,NaN,non-border,B1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12709,A/red_tailedhawk/Pennsylvania/rth_w4/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,rth_w4,red_tailed hawk,wild,NaN,Erie,wild,Pennsylvania,NaN,PA,NaN
12710,A/snowyowl/Pennsylvania/so_w1/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,so_w1,snowy owl,wild,NaN,Erie,wild,Pennsylvania,NaN,PA,NaN
12711,A/turkeyvulture/Pennsylvania/tv_w2/2025,2025-03-05,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,tv_w2,turkey vulture,wild,NaN,Erie,wild,Pennsylvania,NaN,PA,NaN
12712,A/turkeyvulture/Pennsylvania/tv_w3/2025,2025-03-24,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,tv_w3,turkey vulture,wild,NaN,Cumberland,wild,Pennsylvania,NaN,PA,NaN
12713,A/white_wingedscoter/Pennsylvania/wws_w1/2022,2022-12-19,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,wws_w1,white-winged scoter,wild,Anseriformes,Erie,wild,Pennsylvania,NaN,PA,NaN

In [12]:
merge['Genotype'].value_counts()

Genotype
B3.13      2593
B3.2       1555
B2.1       1095
D1.1        900
B4.1        763
           ...
D1.2          1
Minor07       1
Minor13       1
Minor36       1
Minor87       1
Name: count, Length: 78, dtype: int64

In [13]:
merge.to_csv('../../phylo/2026-04-02-fullnortham-meta-w-gtypes.tsv', sep='\t', index=False)

In [15]:
merge = pd.read_csv('../../phylo/2026-04-02-fullnortham-meta-w-gtypes.tsv', sep='\t')
merge

,strain,date,region,country,division,location,host,subtype,originating_lab,submitting_lab,...,id,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state,Genotype
0,A/TrumpeterSwan/BritishColumbia/AIVPHL775/2022,2022-11-28,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,Public Health Agency Of Canada,...,AIVPHL775,trumpeterswan,wild,Anseriformes,NaN,wild,non_PA,NaN,non-border,NaN
1,A/Americanwigeon/NorthCarolina/AH0182517/2022,2022-01-08,North America,Usa,North Carolina,North Carolina,Avian,h5n1,Usda Nwrc Wildlife Services,National Veterinary Services Laboratories Usda,...,AH0182517,American wigeon,wild,Anseriformes,NaN,wild,non_PA,wild,non-border,A1
2,A/turkey/BritishColumbia/AIVPHL128/2022,2022-05-18,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,British Columbia Centre For Disease Control,...,AIVPHL128,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border,B2.1
3,A/turkey/Minnesota/USDA011789003/2022,2022-04-17,North America,Usa,Minnesota,Minnesota,Avian,h5n1,?,?,...,USDA011789003,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border,B2.1
4,A/BlackVulture/Florida/USDA012636001/2022,2022-04-22,North America,Usa,Florida,Florida,Avian,h5n1,?,?,...,USDA012636001,Black Vulture,wild,Raptor,NaN,wild,non_PA,NaN,non-border,B1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12709,A/red_tailedhawk/Pennsylvania/rth_w4/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,rth_w4,red_tailed hawk,wild,NaN,Erie,wild,Pennsylvania,NaN,PA,NaN
12710,A/snowyowl/Pennsylvania/so_w1/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,so_w1,snowy owl,wild,NaN,Erie,wild,Pennsylvania,NaN,PA,NaN
12711,A/turkeyvulture/Pennsylvania/tv_w2/2025,2025-03-05,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,tv_w2,turkey vulture,wild,NaN,Erie,wild,Pennsylvania,NaN,PA,NaN
12712,A/turkeyvulture/Pennsylvania/tv_w3/2025,2025-03-24,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,tv_w3,turkey vulture,wild,NaN,Cumberland,wild,Pennsylvania,NaN,PA,NaN
12713,A/white_wingedscoter/Pennsylvania/wws_w1/2022,2022-12-19,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,wws_w1,white-winged scoter,wild,Anseriformes,Erie,wild,Pennsylvania,NaN,PA,NaN

In [16]:
##FIXING WEIRD CHARACTERS IN SOME COUNTIES!!
merge['county'] = merge['county'].str.replace(r'[^a-zA-Z0-9 ]', '', regex=True)
merge['county'].unique()

array([nan, 'Crawford', 'Lancaster', 'Mehoopany', 'Adams', 'Chester',
       'Erie', 'Lehigh', 'Berks', 'PAunknown', 'Wayne', 'Huntingdon',
       'Monroe', 'Poconosunknown', 'Union', 'Philadelphia', 'unknown',
       'Northumberland', 'Cumberland', 'Lebanon', 'Montgomery'],
      dtype=object)

In [17]:
merge.to_csv('../../phylo/2026-04-02-fullnortham-meta-w-gtypes.tsv', sep='\t', index=False)