In [1]:
import pandas as pd
import numpy as np

In [5]:
df_eca = pd.read_csv('metadata_post_filter_ha.tsv', sep='\t')
df_eca['domesticstatus'].value_counts()

domesticstatus
wild        4805
domestic    3328
unknown     1224
Name: count, dtype: int64

In [9]:
df_eca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9700 entries, 0 to 9699
Data columns (total 39 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   strain           9700 non-null   object
 1   virus            9700 non-null   object
 2   isolate_id       9700 non-null   object
 3   date             9700 non-null   object
 4   region           9700 non-null   object
 5   country          9700 non-null   object
 6   division         9700 non-null   object
 7   location         9700 non-null   object
 8   host             9700 non-null   object
 9   domestic_status  9700 non-null   object
 10  subtype          9700 non-null   object
 11  originating_lab  9700 non-null   object
 12  submitting_lab   9700 non-null   object
 13  authors          9700 non-null   object
 14  PMID             9700 non-null   object
 15  gisaid_clade     9700 non-null   object
 16  h5_clade         9700 non-null   object
 17  n_segments       9700 non-null   int64
 18  genoflu          9305 non-null   object
 19  genoflu_PB2      9130 non-null   object
 20  genoflu_PB1      9124 non-null   object
 21  genoflu_PA       9080 non-null   object
 22  genoflu_HA       9038 non-null   object
 23  genoflu_NP       9139 non-null   object
 24  genoflu_NA       9123 non-null   object
 25  genoflu_MP       9096 non-null   object
 26  genoflu_NS       9148 non-null   object
 27  h5_label_clade   9700 non-null   object
 28  Animal           9700 non-null   object
 29  corrected_host   9334 non-null   object
 30  latin_name       8618 non-null   object
 31  category         9140 non-null   object
 32  order            9585 non-null   object
 33  domesticstatus   9357 non-null   object
 34  source           9334 non-null   object
 35  flyway           8479 non-null   object
 36  geo_region_na    8479 non-null   object
 37  species_group    9700 non-null   object
 38  genotype_ml      9700 non-null   object
dtypes: int64(1), object(38)
memory usage: 2.9+ MB

In [8]:
df_aj = pd.read_csv('../../phylo/2026-03-12_fullgenome_PAd11/data/2026_02_24_meta_merged_northam_PA_fornextstrain.tsv', sep='\t')
df_aj['wild_dom_lbm'].value_counts()

wild_dom_lbm
wild        5030
domestic    4773
unknown     2893
lbm           18
Name: count, dtype: int64

In [14]:
# Select a subset of df2 columns (e.g., 'key' and 'D')
df2_subset = df_eca[['strain', 'domesticstatus']]

# Merge df1 with the subset of df2 on the 'key' column
# 'how="left"' ensures all rows from df1 are included
merged_df = pd.merge(df_aj, df2_subset, on='strain', how='left')

In [17]:
merged_df['wild_dom_lbm'].value_counts()

wild_dom_lbm
wild        5030
domestic    4773
unknown     2893
lbm           18
Name: count, dtype: int64

In [18]:
merged_df['wild_dom_lbm'] = merged_df['wild_dom_lbm'].replace('unknown', np.nan)
merged_df['wild_dom_lbm'] = merged_df['wild_dom_lbm'].fillna(merged_df['domesticstatus'])
merged_df['wild_dom_lbm'].value_counts()

wild_dom_lbm
wild        5867
domestic    4777
unknown      800
lbm           18
Name: count, dtype: int64

In [25]:
merged_df.tail(30)

,strain,date,region,country,division,location,host,subtype,originating_lab,submitting_lab,...,geo_region_na,id,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state
12684,a/turkeyvulture/va/25003128003original/2025,2025-01-10,North America,Usa,Virginia,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,turkeyvulture,wild,NaN,NaN,wild,non_PA,NaN,non-border
12685,a/vulture/ca/25003065001original/2025,2025-01-20,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,vulture,wild,NaN,NaN,wild,non_PA,NaN,non-border
12686,a/vulture/md/25001987001original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,vulture,wild,NaN,NaN,wild,non_PA,NaN,border
12687,a/vulture/md/25001987002original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,vulture,wild,NaN,NaN,wild,non_PA,NaN,border
12688,a/vulture/md/25001987003original/2025,2025-01-15,North America,Usa,Maryland,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,vulture,wild,NaN,NaN,wild,non_PA,NaN,border
12689,a/westerngull/ca/25003273005original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,westerngull,wild,NaN,NaN,wild,non_PA,NaN,non-border
12690,a/westerngull/ca/25003273006original/2025,2025-01-17,North America,Usa,California,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,westerngull,wild,NaN,NaN,wild,non_PA,NaN,non-border
12691,a/woodduck/ky/25002824002original/2025,2025-01-17,North America,Usa,Kentucky,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border
12692,a/woodduck/ms/25002206001original/2025,2025-01-15,North America,Usa,Mississippi,NaN,Avian,h5n1,NaN,NaN,...,NaN,NaN,woodduck,wild,NaN,NaN,wild,non_PA,NaN,non-border
12693,A/baldeagle/Pennsylvania/be_w4/2025,2025-01-17,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,be_w4,bald eagle,wild,NaN,Northumberland,wild,Pennsylvania,NaN,PA
12694,A/blackvulture/Pennsylvania/bv_w10/2025,2025-06-02,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,bv_w10,black vulture,wild,NaN,Lehigh,wild,Pennsylvania,NaN,PA
12695,A/blackvulture/Pennsylvania/bv_w11/2025,2025-06-02,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,bv_w11,black vulture,wild,NaN,Lehigh,wild,Pennsylvania,NaN,PA
12696,A/blackvulture/Pennsylvania/bv_w9/2025,2025-03-24,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,bv_w9,black vulture,wild,NaN,Cumberland,wild,Pennsylvania,NaN,PA
12697,A/chicken/Pennsylvania/c_com1/2025,2025-03-16,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,c_com1,chicken,commercial,Galliformes,Lebanon,domestic,Pennsylvania,NaN,PA
12698,A/chicken/Pennsylvania/c_com2/2025,2025-03-16,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,c_com2,chicken,commercial,Galliformes,Lebanon,domestic,Pennsylvania,NaN,PA
12699,A/chicken/Pennsylvania/c_com3/2025,2025-03-16,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,c_com3,chicken,commercial,Galliformes,Lebanon,domestic,Pennsylvania,NaN,PA
12700,A/chicken/Pennsylvania/c_com4/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,c_com4,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA
12701,A/chicken/Pennsylvania/c_com5/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,c_com5,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA
12702,A/chicken/Pennsylvania/c_com6/2025,2025-01-26,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,c_com6,chicken,commercial,Galliformes,unknown,domestic,Pennsylvania,NaN,PA
12703,A/coopershawk/Pennsylvania/ch_w1/2025,2025-01-17,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,ch_w1,coopers hawk,wild,NaN,Northumberland,wild,Pennsylvania,NaN,PA
12704,A/redfox/Pennsylvania/rf_w2/2025,2025-01-04,North America,Usa,Pennsylvania,Pennsylvania,Nonhuman Mammal,h5n1,UPENN,UPENN,...,Northeast,rf_w2,red fox,wild,NaN,Lehigh,wild,Pennsylvania,NaN,PA
12705,A/redfox/Pennsylvania/rf_w3/2025,2025-02-20,North America,Usa,Pennsylvania,Pennsylvania,Nonhuman Mammal,h5n1,UPENN,UPENN,...,Northeast,rf_w3,red fox,wild,NaN,Montgomery,wild,Pennsylvania,NaN,PA
12706,A/red_tailedhawk/Pennsylvania/rth_w1/2024,2024-02-14,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,rth_w1,red-tailed hawk,wild,Raptor,Union,wild,Pennsylvania,NaN,PA
12707,A/red_tailedhawk/Pennsylvania/rth_w2/2024,2024-01-31,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,rth_w2,red-tailed hawk,wild,Raptor,PA_unknown,wild,Pennsylvania,NaN,PA
12708,A/red_tailedhawk/Pennsylvania/rth_w3/2024,2024-01-31,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,rth_w3,red-tailed hawk,wild,Raptor,PA_unknown,wild,Pennsylvania,NaN,PA
12709,A/red_tailedhawk/Pennsylvania/rth_w4/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,rth_w4,red_tailed hawk,wild,NaN,Erie,wild,Pennsylvania,NaN,PA
12710,A/snowyowl/Pennsylvania/so_w1/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,so_w1,snowy owl,wild,NaN,Erie,wild,Pennsylvania,NaN,PA
12711,A/turkeyvulture/Pennsylvania/tv_w2/2025,2025-03-05,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,tv_w2,turkey vulture,wild,NaN,Erie,wild,Pennsylvania,NaN,PA
12712,A/turkeyvulture/Pennsylvania/tv_w3/2025,2025-03-24,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,tv_w3,turkey vulture,wild,NaN,Cumberland,wild,Pennsylvania,NaN,PA
12713,A/white_wingedscoter/Pennsylvania/wws_w1/2022,2022-12-19,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,wws_w1,white-winged scoter,wild,Anseriformes,Erie,wild,Pennsylvania,NaN,PA

In [103]:
merged_df['division'].unique()

array(['British Columbia', 'North Carolina', 'Minnesota', 'Florida',
       'South Carolina', 'North Dakota', 'Washington', 'New Mexico',
       'South Dakota', 'Oklahoma', 'Montana', 'Alaska', 'Idaho',
       'Michigan', 'New Jersey', 'Massachusetts', 'Iowa', 'Virginia',
       'Ohio', 'Colorado', 'Kansas', 'New York', 'Oregon',
       'New Hampshire', 'Missouri', 'Texas', 'California', 'Maryland',
       'Maine', 'Wyoming', 'Tennessee', 'Delaware', 'Saskatchewan',
       'Arkansas', 'Louisiana', 'Wisconsin', 'Georgia', 'Pennsylvania',
       'Indiana', 'Alberta', 'Connecticut', 'Nebraska',
       'Prince Edward Island', 'Kentucky', 'Arizona', 'Utah', 'Alabama',
       'Ontario', 'Manitoba', 'Illinois', 'Newfoundland', 'Nevada',
       'Costa Rica', 'Mississippi', 'Usa', 'Honduras', 'Panama',
       'Vermont', 'Nova Scotia', 'Guatemala', 'Rhode Island', 'Canada',
       'Quebec', 'Hawaii', 'Nunavut', 'New Brunswick', 'Newyork',
       'Southcarolina', 'Northdakota', 'Westvirginia', 'Northcarolina',
       'Newjersey', 'Newmexico', 'Southdakota', 'Ciudaddemexico',
       'Mexicostate', 'Durango', 'Newhampshire', 'Sonora'], dtype=object)

In [107]:
import pandas as pd
from difflib import get_close_matches

# Step 1: Define canonical names (your known-good list)
canonical_states = [
    # US States
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
    'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
    'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
    'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
    'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
    'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina',
    'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
    'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas',
    'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
    'Wisconsin', 'Wyoming',
    # Canadian Provinces
    'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick',
    'Newfoundland', 'Nova Scotia', 'Nunavut', 'Ontario',
    'Prince Edward Island', 'Quebec', 'Saskatchewan',
    # Central America / Mexico
    'Costa Rica', 'Guatemala', 'Honduras', 'Panama',
    'Ciudad de Mexico', 'Mexico State', 'Durango', 'Sonora',
    # Other
    'Canada', 'Usa',
]

# Step 2: Manual overrides for cases fuzzy matching may get wrong
manual_map = {
    'Newyork':          'New York',
    'Southcarolina':    'South Carolina',
    'Northdakota':      'North Dakota',
    'Westvirginia':     'West Virginia',
    'Northcarolina':    'North Carolina',
    'Newjersey':        'New Jersey',
    'Newmexico':        'New Mexico',
    'Southdakota':      'South Dakota',
    'Newhampshire':     'New Hampshire',
    'Ciudaddemexico':   'Ciudad de Mexico',
    'Mexicostate':      'Mexico State',
}

# Step 3: Normalization function
def normalize_state(val):
    if pd.isna(val):
        return val
    val = str(val).strip()
    
    # Check manual overrides first (case-insensitive)
    title_val = val.title()
    if title_val in manual_map:
        return manual_map[title_val]
    
    # If already canonical, return as-is
    if val in canonical_states:
        return val
    
    # Try title-casing it first
    if title_val in canonical_states:
        return title_val

    # Fuzzy match as last resort
    matches = get_close_matches(title_val, canonical_states, n=1, cutoff=0.75)
    return matches[0] if matches else val  # return original if no match found

# Step 4: Apply
merged_df['state_clean'] = merged_df['division'].apply(normalize_state)

# Step 5: Audit anything that didn't resolve cleanly
unresolved = merged_df[merged_df['state_clean'] == merged_df['division']]['division'].unique()
print("Review these manually:", unresolved)

Review these manually: ['British Columbia' 'North Carolina' 'Minnesota' 'Florida'
 'South Carolina' 'North Dakota' 'Washington' 'New Mexico' 'South Dakota'
 'Oklahoma' 'Montana' 'Alaska' 'Idaho' 'Michigan' 'New Jersey'
 'Massachusetts' 'Iowa' 'Virginia' 'Ohio' 'Colorado' 'Kansas' 'New York'
 'Oregon' 'New Hampshire' 'Missouri' 'Texas' 'California' 'Maryland'
 'Maine' 'Wyoming' 'Tennessee' 'Delaware' 'Saskatchewan' 'Arkansas'
 'Louisiana' 'Wisconsin' 'Georgia' 'Pennsylvania' 'Indiana' 'Alberta'
 'Connecticut' 'Nebraska' 'Prince Edward Island' 'Kentucky' 'Arizona'
 'Utah' 'Alabama' 'Ontario' 'Manitoba' 'Illinois' 'Newfoundland' 'Nevada'
 'Costa Rica' 'Mississippi' 'Usa' 'Honduras' 'Panama' 'Vermont'
 'Nova Scotia' 'Guatemala' 'Rhode Island' 'Canada' 'Quebec' 'Hawaii'
 'Nunavut' 'New Brunswick' 'Durango' 'Sonora']

In [110]:
merged_df['division'] = merged_df['state_clean']
merged_df.drop(columns=['state_clean'], inplace=True)

KeyError: 'state_clean'

In [112]:
border_states = ['New York', 'New Jersey', 'Delaware', 'Ohio', 'Maryland', 'West Virginia']

merged_df['border_state'] = np.select(
    [merged_df['division'] == 'Pennsylvania', merged_df['division'].isin(border_states)],
    ['PA', 'border'],
    default='non-border'
)

,strain,date,region,country,division,location,host,subtype,originating_lab,submitting_lab,...,geo_region_na,id,species,domestic_status,species_group,county,wild_dom_lbm,pa_status,domesticstatus,border_state
0,A/TrumpeterSwan/BritishColumbia/AIVPHL775/2022,2022-11-28,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,Public Health Agency Of Canada,...,Canada,AIVPHL775,trumpeterswan,wild,Anseriformes,NaN,wild,non_PA,NaN,non-border
1,A/Americanwigeon/NorthCarolina/AH0182517/2022,2022-01-08,North America,Usa,North Carolina,North Carolina,Avian,h5n1,Usda Nwrc Wildlife Services,National Veterinary Services Laboratories Usda,...,South,AH0182517,American wigeon,wild,Anseriformes,NaN,wild,non_PA,wild,non-border
2,A/turkey/BritishColumbia/AIVPHL128/2022,2022-05-18,North America,Canada,British Columbia,British Columbia,Avian,h5n1,B.c. Centre For Disease Control,British Columbia Centre For Disease Control,...,Canada,AIVPHL128,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border
3,A/turkey/Minnesota/USDA011789003/2022,2022-04-17,North America,Usa,Minnesota,Minnesota,Avian,h5n1,?,?,...,Midwest,USDA011789003,turkey,unknown,Galliformes,NaN,NaN,non_PA,NaN,non-border
4,A/BlackVulture/Florida/USDA012636001/2022,2022-04-22,North America,Usa,Florida,Florida,Avian,h5n1,?,?,...,South,USDA012636001,Black Vulture,wild,Raptor,NaN,wild,non_PA,NaN,non-border
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12709,A/red_tailedhawk/Pennsylvania/rth_w4/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,rth_w4,red_tailed hawk,wild,NaN,Erie,wild,Pennsylvania,NaN,PA
12710,A/snowyowl/Pennsylvania/so_w1/2025,2025-03-06,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,so_w1,snowy owl,wild,NaN,Erie,wild,Pennsylvania,NaN,PA
12711,A/turkeyvulture/Pennsylvania/tv_w2/2025,2025-03-05,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,tv_w2,turkey vulture,wild,NaN,Erie,wild,Pennsylvania,NaN,PA
12712,A/turkeyvulture/Pennsylvania/tv_w3/2025,2025-03-24,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,tv_w3,turkey vulture,wild,NaN,Cumberland,wild,Pennsylvania,NaN,PA
12713,A/white_wingedscoter/Pennsylvania/wws_w1/2022,2022-12-19,North America,Usa,Pennsylvania,Pennsylvania,Avian,h5n1,UPENN,UPENN,...,Northeast,wws_w1,white-winged scoter,wild,Anseriformes,Erie,wild,Pennsylvania,NaN,PA

In [113]:
merged_df['border_state'].value_counts()

border_state
non-border    11852
border          495
PA              367
Name: count, dtype: int64

In [114]:
merged_df.to_csv('../../phylo/2026-03-13-northam-PA-meta-updateddomstat.tsv', sep='\t', index=False)

In [17]:
##need to modify position in the HA csv to be by H5 numbering not H3
ha = pd.read_csv('../../seq/analysis/functional_sites_2019_bygene/scrape_sites/Clean_HA.csv')
ha

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified
0,1,4,-1,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN
1,2,4,5,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN
2,3,4,17,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN
3,4,4,17,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN
4,5,4,17,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,552,4,548,I548Y,I549Y,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,Y,NaN,NaN,NaN
552,553,4,550,I550W,I551W,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,W,NaN,NaN,NaN
553,554,4,434,E434K,E434K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,E,K,NaN,NaN,NaN
554,555,4,443,N443K,N443K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,N,K,NaN,NaN,NaN
555,556,4,31,E31K,E21K,NaN,Cotter et al. PLoS Pathog. 2014,10.1371/journal.ppat.1003831,E,K,NaN,NaN,NaN

In [18]:
ha.rename(columns={"Unnamed: 0":""}, inplace=True)
ha

,,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified
0,1,4,-1,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN
1,2,4,5,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN
2,3,4,17,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN
3,4,4,17,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN
4,5,4,17,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,552,4,548,I548Y,I549Y,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,Y,NaN,NaN,NaN
552,553,4,550,I550W,I551W,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,W,NaN,NaN,NaN
553,554,4,434,E434K,E434K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,E,K,NaN,NaN,NaN
554,555,4,443,N443K,N443K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,N,K,NaN,NaN,NaN
555,556,4,31,E31K,E21K,NaN,Cotter et al. PLoS Pathog. 2014,10.1371/journal.ppat.1003831,E,K,NaN,NaN,NaN

In [19]:
ha["h5_AA"] = ha["Mutation H5 numbering"].str.extract(r"(\d+)").astype(int)
ha["h5_AA"] = ha["Mutation H5 numbering"].str.extract(r"(\d+)")[0].astype("Int64")
ha

,,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,h5_AA
0,1,4,-1,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,11
1,2,4,5,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,6
2,3,4,17,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,7
3,4,4,17,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,7
4,5,4,17,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,552,4,548,I548Y,I549Y,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,Y,NaN,NaN,NaN,549
552,553,4,550,I550W,I551W,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,W,NaN,NaN,NaN,551
553,554,4,434,E434K,E434K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,E,K,NaN,NaN,NaN,434
554,555,4,443,N443K,N443K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,N,K,NaN,NaN,NaN,443
555,556,4,31,E31K,E21K,NaN,Cotter et al. PLoS Pathog. 2014,10.1371/journal.ppat.1003831,E,K,NaN,NaN,NaN,21

In [20]:
##replace values in H5
ha['Position'] = ha['h5_AA']
ha

,,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,h5_AA
0,1,4,11,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,11
1,2,4,6,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,6
2,3,4,7,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,7
3,4,4,7,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,7
4,5,4,7,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,552,4,549,I548Y,I549Y,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,Y,NaN,NaN,NaN,549
552,553,4,551,I550W,I551W,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,W,NaN,NaN,NaN,551
553,554,4,434,E434K,E434K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,E,K,NaN,NaN,NaN,434
554,555,4,443,N443K,N443K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,N,K,NaN,NaN,NaN,443
555,556,4,21,E31K,E21K,NaN,Cotter et al. PLoS Pathog. 2014,10.1371/journal.ppat.1003831,E,K,NaN,NaN,NaN,21

In [21]:
##drop h5_aa col
ha.drop(columns=['h5_AA'], inplace=True)
ha

,,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified
0,1,4,11,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN
1,2,4,6,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN
2,3,4,7,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN
3,4,4,7,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN
4,5,4,7,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,552,4,549,I548Y,I549Y,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,Y,NaN,NaN,NaN
552,553,4,551,I550W,I551W,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,W,NaN,NaN,NaN
553,554,4,434,E434K,E434K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,E,K,NaN,NaN,NaN
554,555,4,443,N443K,N443K,NaN,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,N,K,NaN,NaN,NaN
555,556,4,21,E31K,E21K,NaN,Cotter et al. PLoS Pathog. 2014,10.1371/journal.ppat.1003831,E,K,NaN,NaN,NaN

In [22]:
ha.to_csv('../../seq/analysis/functional_sites_2019_bygene/scrape_sites/HA_h5num_position.csv', index=False)

In [23]:
###now wanna add in new func annotations db stuff
import glob

files = glob.glob("../../seq/analysis/functional_sites_2019_bygene/scrape_sites/*.csv")

df = pd.concat((pd.read_csv(f) for f in files), ignore_index=True)

df.to_csv("../../seq/analysis/functional_sites_2019_bygene/scrape_sites/combined.csv", index=False)

In [24]:
df = pd.read_csv('../../seq/analysis/functional_sites_2019_bygene/scrape_sites/combined.csv')

In [25]:
df

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes
0,1,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN
1,2,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN
2,3,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN
4,5,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,62,8,69.0,NaN,NaN,H5N2,Wu et al. Virol. J. 2016,10.1186/s12985-016-0612-5,E,E69G,NaN,NaN,NaN,G,NaN,NaN
1245,63,8,75.0,NaN,NaN,NaN,Mänz et al. Nat. Commun. 2012,10.1038/ncomms1804,E,E75G,NaN,NaN,NaN,G,NaN,NaN
1246,64,8,88.0,NaN,NaN,H3N2,Ping et al. PLoS One 2011,10.1371/journal.pone.0021740,K,K88R,NaN,NaN,NaN,R,NaN,NaN
1247,65,8,110.0,NaN,NaN,H9N2,Sun et al. Sci. Adv. 2023,10.1126/sciadv.adg5175,G,G110E,NaN,NaN,NaN,E,NaN,NaN
1248,66,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
segment_to_gene = {
    1: "PB2",
    2: "PB1",
    3: "PA",
    4: "HA",
    5: "NP",
    6: "NA",
    7: "M",
    8: "NS"
}

df["Gene"] = df["Segment"].map(segment_to_gene)
df

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes,Gene
0,1,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN,HA
1,2,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
2,3,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN,HA
3,4,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
4,5,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN,HA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,62,8,69.0,NaN,NaN,H5N2,Wu et al. Virol. J. 2016,10.1186/s12985-016-0612-5,E,E69G,NaN,NaN,NaN,G,NaN,NaN,NS
1245,63,8,75.0,NaN,NaN,NaN,Mänz et al. Nat. Commun. 2012,10.1038/ncomms1804,E,E75G,NaN,NaN,NaN,G,NaN,NaN,NS
1246,64,8,88.0,NaN,NaN,H3N2,Ping et al. PLoS One 2011,10.1371/journal.pone.0021740,K,K88R,NaN,NaN,NaN,R,NaN,NaN,NS
1247,65,8,110.0,NaN,NaN,H9N2,Sun et al. Sci. Adv. 2023,10.1126/sciadv.adg5175,G,G110E,NaN,NaN,NaN,E,NaN,NaN,NS
1248,66,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NS

In [33]:
# dropping HA sites that aren't H5N1 and NA sites that aren't N1
# The condition to DROP is: (~df['A'].str.contains('xy')) & (df['B'] == 'y')
# Therefore, we KEEP everything else by using ~ at the start
df_cleaned = df[~((~df['Which virus'].str.contains('H5N1', na=False)) & (df['Gene'] == 'HA'))]
df_cleaned

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes,Gene
0,1,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN,HA
1,2,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
2,3,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN,HA
3,4,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
4,5,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN,HA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,62,8,69.0,NaN,NaN,H5N2,Wu et al. Virol. J. 2016,10.1186/s12985-016-0612-5,E,E69G,NaN,NaN,NaN,G,NaN,NaN,NS
1245,63,8,75.0,NaN,NaN,NaN,Mänz et al. Nat. Commun. 2012,10.1038/ncomms1804,E,E75G,NaN,NaN,NaN,G,NaN,NaN,NS
1246,64,8,88.0,NaN,NaN,H3N2,Ping et al. PLoS One 2011,10.1371/journal.pone.0021740,K,K88R,NaN,NaN,NaN,R,NaN,NaN,NS
1247,65,8,110.0,NaN,NaN,H9N2,Sun et al. Sci. Adv. 2023,10.1126/sciadv.adg5175,G,G110E,NaN,NaN,NaN,E,NaN,NaN,NS
1248,66,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NS

In [34]:
df = df_cleaned[~((~df_cleaned['Which virus'].str.contains('N1', na=False)) & (df['Gene'] == 'NA'))]
df

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_89697/764847798.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df_cleaned[~((~df_cleaned['Which virus'].str.contains('N1', na=False)) & (df['Gene'] == 'NA'))]

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes,Gene
0,1,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN,HA
1,2,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
2,3,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN,HA
3,4,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
4,5,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN,HA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,62,8,69.0,NaN,NaN,H5N2,Wu et al. Virol. J. 2016,10.1186/s12985-016-0612-5,E,E69G,NaN,NaN,NaN,G,NaN,NaN,NS
1245,63,8,75.0,NaN,NaN,NaN,Mänz et al. Nat. Commun. 2012,10.1038/ncomms1804,E,E75G,NaN,NaN,NaN,G,NaN,NaN,NS
1246,64,8,88.0,NaN,NaN,H3N2,Ping et al. PLoS One 2011,10.1371/journal.pone.0021740,K,K88R,NaN,NaN,NaN,R,NaN,NaN,NS
1247,65,8,110.0,NaN,NaN,H9N2,Sun et al. Sci. Adv. 2023,10.1126/sciadv.adg5175,G,G110E,NaN,NaN,NaN,E,NaN,NaN,NS
1248,66,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NS

In [35]:
df.head(30)

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes,Gene
0,1,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN,HA
1,2,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
2,3,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN,HA
3,4,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
4,5,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN,HA
5,6,4,7.0,Y17W,Y7W,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,W,NaN,NaN,NaN,NaN,NaN,NaN,HA
6,7,4,7.0,Y17C,Y7C,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,C,NaN,NaN,NaN,NaN,NaN,NaN,HA
8,9,4,8.0,H18C,H8C,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,H,C,NaN,NaN,NaN,NaN,NaN,NaN,HA
9,10,4,8.0,H18F,H8F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,H,F,NaN,NaN,NaN,NaN,NaN,NaN,HA
10,11,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN,HA
11,12,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
12,13,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN,HA
13,14,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN,HA
14,15,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN,HA
15,16,4,7.0,Y17W,Y7W,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,W,NaN,NaN,NaN,NaN,NaN,NaN,HA
16,17,4,7.0,Y17C,Y7C,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,C,NaN,NaN,NaN,NaN,NaN,NaN,HA
18,19,4,8.0,H18C,H8C,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,H,C,NaN,NaN,NaN,NaN,NaN,NaN,HA
19,20,4,8.0,H18F,H8F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,H,F,NaN,NaN,NaN,NaN,NaN,NaN,HA
20,21,4,8.0,H18Q,H8Q,H5N1,Reed et al. J. Virol. 2009,10.1128/JVI.02238-08,H,Q,NaN,NaN,NaN,NaN,NaN,NaN,HA
21,22,4,9.0,A19N,A9N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,A,N,NaN,NaN,NaN,NaN,NaN,NaN,HA
22,23,4,14.0,E24I,E14I,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,E,I,NaN,NaN,NaN,NaN,NaN,NaN,HA
23,24,4,15.0,Q25W,Q15W,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Q,W,NaN,NaN,NaN,NaN,NaN,NaN,HA
24,25,4,19.0,I29M,I19M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,M,NaN,NaN,NaN,NaN,NaN,NaN,HA
25,26,4,19.0,I29S,I19S,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,S,NaN,NaN,NaN,NaN,NaN,NaN,HA
26,27,4,19.0,I29W,I19W,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,W,NaN,NaN,NaN,NaN,NaN,NaN,HA
27,28,4,19.0,I29Q,I19Q,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,I,Q,NaN,NaN,NaN,NaN,NaN,NaN,HA
28,29,4,20.0,M30L,M20L,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,M,L,NaN,NaN,NaN,NaN,NaN,NaN,HA
29,30,4,20.0,M30Y,M20Y,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,M,Y,NaN,NaN,NaN,NaN,NaN,NaN,HA
30,31,4,20.0,M30I,M20I,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,M,I,NaN,NaN,NaN,NaN,NaN,NaN,HA
31,32,4,21.0,E31S,E21S,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,E,S,NaN,NaN,NaN,NaN,NaN,NaN,HA

In [36]:
#jk it already has position

# df["h5_AA"] = df["Mutation H5 numbering"].str.extract(r"(\d+)").astype(int)
# df["h5_AA"] = df["Mutation H5 numbering"].str.extract(r"(\d+)")[0].astype("Int64")

df["gene_pos"] = df["Gene"] + "_" + df['Position'].astype(str)

df["gene_pos"] = df["gene_pos"].astype(str).str.replace(r"\.0$", "", regex=True)

df

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_89697/4068204861.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["gene_pos"] = df["Gene"] + "_" + df['Position'].astype(str)
/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_89697/4068204861.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["gene_pos"] = df["gene_pos"].astype(str).str.replace(r"\.0$", "", regex=True)

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes,Gene,gene_pos
0,1,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_11
1,2,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_6
2,3,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7
3,4,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7
4,5,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,62,8,69.0,NaN,NaN,H5N2,Wu et al. Virol. J. 2016,10.1186/s12985-016-0612-5,E,E69G,NaN,NaN,NaN,G,NaN,NaN,NS,NS_69
1245,63,8,75.0,NaN,NaN,NaN,Mänz et al. Nat. Commun. 2012,10.1038/ncomms1804,E,E75G,NaN,NaN,NaN,G,NaN,NaN,NS,NS_75
1246,64,8,88.0,NaN,NaN,H3N2,Ping et al. PLoS One 2011,10.1371/journal.pone.0021740,K,K88R,NaN,NaN,NaN,R,NaN,NaN,NS,NS_88
1247,65,8,110.0,NaN,NaN,H9N2,Sun et al. Sci. Adv. 2023,10.1126/sciadv.adg5175,G,G110E,NaN,NaN,NaN,E,NaN,NaN,NS,NS_110
1248,66,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NS,NS_nan

In [37]:
df["change_info"] = df["Which virus"] + "_" + df['Mutation H5 numbering'].astype(str)
df

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_89697/2565096759.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["change_info"] = df["Which virus"] + "_" + df['Mutation H5 numbering'].astype(str)

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes,Gene,gene_pos,change_info
0,1,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_11,H5N1_L-11N
1,2,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_6,H5N1_V-6T
2,3,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7,H5N1_Y7M
3,4,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7,H5N1_Y7T
4,5,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7,H5N1_Y7F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,62,8,69.0,NaN,NaN,H5N2,Wu et al. Virol. J. 2016,10.1186/s12985-016-0612-5,E,E69G,NaN,NaN,NaN,G,NaN,NaN,NS,NS_69,H5N2_nan
1245,63,8,75.0,NaN,NaN,NaN,Mänz et al. Nat. Commun. 2012,10.1038/ncomms1804,E,E75G,NaN,NaN,NaN,G,NaN,NaN,NS,NS_75,NaN
1246,64,8,88.0,NaN,NaN,H3N2,Ping et al. PLoS One 2011,10.1371/journal.pone.0021740,K,K88R,NaN,NaN,NaN,R,NaN,NaN,NS,NS_88,H3N2_nan
1247,65,8,110.0,NaN,NaN,H9N2,Sun et al. Sci. Adv. 2023,10.1126/sciadv.adg5175,G,G110E,NaN,NaN,NaN,E,NaN,NaN,NS,NS_110,H9N2_nan
1248,66,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NS,NS_nan,NaN

In [48]:
##if change info is nan, then put paper ref 
df['change_info'] = df['change_info'].replace('', pd.NA).fillna(df['Paper(s)'])
df

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_89697/1499294368.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['change_info'] = df['change_info'].replace('', pd.NA).fillna(df['Paper(s)'])

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes,Gene,gene_pos,change_info
0,1,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_11,H5N1_L-11N
1,2,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_6,H5N1_V-6T
2,3,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7,H5N1_Y7M
3,4,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7,H5N1_Y7T
4,5,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7,H5N1_Y7F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,62,8,69.0,NaN,NaN,H5N2,Wu et al. Virol. J. 2016,10.1186/s12985-016-0612-5,E,E69G,NaN,NaN,NaN,G,NaN,NaN,NS,NS_69,H5N2_nan
1245,63,8,75.0,NaN,NaN,NaN,Mänz et al. Nat. Commun. 2012,10.1038/ncomms1804,E,E75G,NaN,NaN,NaN,G,NaN,NaN,NS,NS_75,Mänz et al. Nat. Commun. 2012
1246,64,8,88.0,NaN,NaN,H3N2,Ping et al. PLoS One 2011,10.1371/journal.pone.0021740,K,K88R,NaN,NaN,NaN,R,NaN,NaN,NS,NS_88,H3N2_nan
1247,65,8,110.0,NaN,NaN,H9N2,Sun et al. Sci. Adv. 2023,10.1126/sciadv.adg5175,G,G110E,NaN,NaN,NaN,E,NaN,NaN,NS,NS_110,H9N2_nan
1248,66,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NS,NS_nan,NaN

In [38]:
##filter db to just h5s? --not doing this bc did other filter, don't want to eliminate other NA N1s that are not with H5
# df_filtered = df[
#     df["Which virus"].isna() | df["Which virus"].astype(str).str.contains("H5")
# ]
# # df_filtered = df[
# #     (~df["Gene"].isin(["HA","NA"])) |  # keep rows that are NOT HA or NA
# #     (df["Gene"].isin(["HA","NA"]) & (df["Which virus"].isna() | df["Which virus"].str.contains("H5", na=False)))
# # ]
# df_filtered

,Unnamed: 0,Segment,Position,Mutation H3 numbering,Mutation H5 numbering,Which virus,Paper(s),DOI,WT,Mutation,How was the mutation discovered,Notes,Experimentally verified,Mutant,Extra notes,Further notes,Gene,gene_pos,change_info
0,1,4,11.0,L-1N,L-11N,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,L,N,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_11,H5N1_L-11N
1,2,4,6.0,V5T,V-6T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,V,T,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_6,H5N1_V-6T
2,3,4,7.0,Y17M,Y7M,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,M,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7,H5N1_Y7M
3,4,4,7.0,Y17T,Y7T,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,T,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7,H5N1_Y7T
4,5,4,7.0,Y17F,Y7F,H5N1,Dadonaite et al. PLoS Biol. 2024,10.1371/journal.pbio.3002916,Y,F,NaN,NaN,NaN,NaN,NaN,NaN,HA,HA_7,H5N1_Y7F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1241,59,8,48.0,NaN,NaN,NaN,Wei et al. J. Virol. 2014,10.1128/jvi.01679-14,T,T48N,NaN,NaN,NaN,N,NaN,NaN,NS,NS_48,NaN
1242,60,8,51.0,NaN,NaN,H5N1,Imai et al. PLoS Pathog. 2010,10.1371/journal.ppat.1001106,I,I51M,NaN,NaN,NaN,M,NaN,NaN,NS,NS_51,H5N1_nan
1244,62,8,69.0,NaN,NaN,H5N2,Wu et al. Virol. J. 2016,10.1186/s12985-016-0612-5,E,E69G,NaN,NaN,NaN,G,NaN,NaN,NS,NS_69,H5N2_nan
1245,63,8,75.0,NaN,NaN,NaN,Mänz et al. Nat. Commun. 2012,10.1038/ncomms1804,E,E75G,NaN,NaN,NaN,G,NaN,NaN,NS,NS_75,NaN
1248,66,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NS,NS_nan,NaN

In [49]:
subset = df[['Gene', 'Position', 'Notes', 'gene_pos', 'Segment', 'change_info']]
subset

     Gene  Position  Notes gene_pos  Segment                    change_info
0      HA      11.0    NaN    HA_11        4                     H5N1_L-11N
1      HA       6.0    NaN     HA_6        4                      H5N1_V-6T
2      HA       7.0    NaN     HA_7        4                       H5N1_Y7M
3      HA       7.0    NaN     HA_7        4                       H5N1_Y7T
4      HA       7.0    NaN     HA_7        4                       H5N1_Y7F
...   ...       ...    ...      ...      ...                            ...
1244   NS      69.0    NaN    NS_69        8                       H5N2_nan
1245   NS      75.0    NaN    NS_75        8  Mänz et al. Nat. Commun. 2012
1246   NS      88.0    NaN    NS_88        8                       H3N2_nan
1247   NS     110.0    NaN   NS_110        8                       H9N2_nan
1248   NS       NaN    NaN   NS_nan        8                            NaN

[1176 rows x 6 columns]

In [50]:
subset.rename(columns={'Position': 'Amino_Acid', 'Notes':'Type', 'Segment':'gene'}, inplace=True)
subset

/var/folders/8h/zkgpnzwj7f9d82wldp_d4h_w0000gs/T/ipykernel_89697/3660961416.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset.rename(columns={'Position': 'Amino_Acid', 'Notes':'Type', 'Segment':'gene'}, inplace=True)

     Gene  Amino_Acid  Type gene_pos  gene                    change_info
0      HA        11.0   NaN    HA_11     4                     H5N1_L-11N
1      HA         6.0   NaN     HA_6     4                      H5N1_V-6T
2      HA         7.0   NaN     HA_7     4                       H5N1_Y7M
3      HA         7.0   NaN     HA_7     4                       H5N1_Y7T
4      HA         7.0   NaN     HA_7     4                       H5N1_Y7F
...   ...         ...   ...      ...   ...                            ...
1244   NS        69.0   NaN    NS_69     8                       H5N2_nan
1245   NS        75.0   NaN    NS_75     8  Mänz et al. Nat. Commun. 2012
1246   NS        88.0   NaN    NS_88     8                       H3N2_nan
1247   NS       110.0   NaN   NS_110     8                       H9N2_nan
1248   NS         NaN   NaN   NS_nan     8                            NaN

[1176 rows x 6 columns]

In [41]:
db = pd.read_csv('../../seq/analysis/merged_flumina_2019_1aa.tsv', sep='\t')
db["Gene"] = db["Gene"].fillna("NA")

In [42]:
db

,Gene,Amino_Acid,Type,gene_pos,gene,change_info
0,HA,91.0,human-adaptation,HA_91,NaN,NaN
1,HA,154.0,pathogenicity,HA_154,NaN,NaN
2,HA,158.0,host-adaptation,HA_158,NaN,NaN
3,HA,192.0,human-adaptation,HA_192,NaN,NaN
4,HA,228.0,human-adaptation,HA_228,NaN,NaN
...,...,...,...,...,...,...
139,PB2,636.0,sequence alteration,PB2_636,PB2,determinant-of-host-range
140,PB2,271.0,sequence alteration,PB2_271,PB2,determinant-of-host-range
141,PB2,667.0,sequence alteration,PB2_667,PB2,determinant-of-transmission
142,PB2,702.0,sequence alteration,PB2_702,PB2,determinant-of-transmission
143,PB2,256.0,functional,PB2_256,PB2,polymerase-activity

In [62]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gene         144 non-null    object
 1   Amino_Acid   143 non-null    float64
 2   Type         144 non-null    object
 3   gene_pos     144 non-null    object
 4   gene         103 non-null    object
 5   change_info  102 non-null    object
dtypes: float64(1), object(5)
memory usage: 6.9+ KB

In [51]:
merge = pd.concat([db, subset])
merge

,Gene,Amino_Acid,Type,gene_pos,gene,change_info
0,HA,91.0,human-adaptation,HA_91,NaN,NaN
1,HA,154.0,pathogenicity,HA_154,NaN,NaN
2,HA,158.0,host-adaptation,HA_158,NaN,NaN
3,HA,192.0,human-adaptation,HA_192,NaN,NaN
4,HA,228.0,human-adaptation,HA_228,NaN,NaN
...,...,...,...,...,...,...
1244,NS,69.0,NaN,NS_69,8,H5N2_nan
1245,NS,75.0,NaN,NS_75,8,Mänz et al. Nat. Commun. 2012
1246,NS,88.0,NaN,NS_88,8,H3N2_nan
1247,NS,110.0,NaN,NS_110,8,H9N2_nan
1248,NS,NaN,NaN,NS_nan,8,NaN

In [52]:
merge.drop_duplicates(subset=['gene_pos'], keep='first', inplace=True)
merge

,Gene,Amino_Acid,Type,gene_pos,gene,change_info
0,HA,91.0,human-adaptation,HA_91,NaN,NaN
1,HA,154.0,pathogenicity,HA_154,NaN,NaN
2,HA,158.0,host-adaptation,HA_158,NaN,NaN
3,HA,192.0,human-adaptation,HA_192,NaN,NaN
4,HA,228.0,human-adaptation,HA_228,NaN,NaN
...,...,...,...,...,...,...
1244,NS,69.0,NaN,NS_69,8,H5N2_nan
1245,NS,75.0,NaN,NS_75,8,Mänz et al. Nat. Commun. 2012
1246,NS,88.0,NaN,NS_88,8,H3N2_nan
1247,NS,110.0,NaN,NS_110,8,H9N2_nan
1248,NS,NaN,NaN,NS_nan,8,NaN

In [53]:
merge['Type'] = merge['Type'].replace('', pd.NA).fillna(merge['change_info'])
merge

,Gene,Amino_Acid,Type,gene_pos,gene,change_info
0,HA,91.0,human-adaptation,HA_91,NaN,NaN
1,HA,154.0,pathogenicity,HA_154,NaN,NaN
2,HA,158.0,host-adaptation,HA_158,NaN,NaN
3,HA,192.0,human-adaptation,HA_192,NaN,NaN
4,HA,228.0,human-adaptation,HA_228,NaN,NaN
...,...,...,...,...,...,...
1244,NS,69.0,H5N2_nan,NS_69,8,H5N2_nan
1245,NS,75.0,Mänz et al. Nat. Commun. 2012,NS_75,8,Mänz et al. Nat. Commun. 2012
1246,NS,88.0,H3N2_nan,NS_88,8,H3N2_nan
1247,NS,110.0,H9N2_nan,NS_110,8,H9N2_nan
1248,NS,NaN,NaN,NS_nan,8,NaN

In [55]:
merge.to_csv('../../comm-pa/sample_data/2026-05-11-functional-db-fullmerge.tsv', sep='\t', index=False)