In [15]:
import pandas as pd
import numpy as np
from pathlib import Path

In [ ]:
##i want to get coverage info for how many bases have 100X coverage across both reps
##going to try to get this info from the depth files

In [16]:
#transform txt to tsv and add headers
# root = Path("/Users/asjaeger/Desktop/project_source/hpai-PA/seq/illumina-pipeline/data")
# root = Path("/Users/asjaeger/Desktop/project_source/hpai-PA/seq/data")
root = Path("/Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data")


header = "gene\tpos\tcvg\n"

for txt_file in root.rglob("remapping-2/depth.txt"):
    tsv_file = txt_file.with_suffix(".tsv")

    with txt_file.open("r") as fin, tsv_file.open("w") as fout:
        fout.write(header)
        for line in fin:
            fout.write("\t".join(line.split()) + "\n")

    print(f"Converted with header: {txt_file} → {tsv_file}")

Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_4/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_4/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run4_RT_NC_1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run4_RT_NC_1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_3/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_3/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm2/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm2/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm2/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm2/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cl_c2/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cl_c2/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_2/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_2/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_5/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_5/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm3/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm3/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm3/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm3/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm4/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm4/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm4/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm4/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/rt_nc_run9/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/rt_nc_run9/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC4_run9/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC4_run9/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com3/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com3/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com3/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com3/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com4/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com4/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com4/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com4/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/rt_nc3_run10/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/rt_nc3_run10/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_PCR_NC_1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_PCR_NC_1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run4_PCR_NC_1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run4_PCR_NC_1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com3/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com3/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com3/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com3/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com5/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com5/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com5/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com5/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com2/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com2/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com2/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com2/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_RT_NC_1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_RT_NC_1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com2/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com2/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com2/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com2/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cb_com1/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cb_com1/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cb_com1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cb_com1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCR_NC1_run9/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCR_NC1_run9/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com3/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com3/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com3/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com3/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_com1/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_com1/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_com1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_com1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com4/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com4/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com4/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com4/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC3_run9/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC3_run9/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com3/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com3/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com3/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com3/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com5/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com5/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com5/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com5/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com2/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com2/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com2/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com2/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com2/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com2/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com2/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com2/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/gn_lbm1/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/gn_lbm1/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/gn_lbm1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/gn_lbm1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm2/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm2/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm2/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm2/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/RTNC2_run8/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/RTNC2_run8/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC2_run8/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC2_run8/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm5/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm5/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm5/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm5/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_lbm1/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_lbm1/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_lbm1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_lbm1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm4/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm4/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm3/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm3/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm3/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm3/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/rt_nc2_run10/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/rt_nc2_run10/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm1/replicate-2/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm1/replicate-2/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/pcr_nc4_run10/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/pcr_nc4_run10/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC1_run8/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC1_run8/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_6/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_6/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cl_c1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cl_c1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_1/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_1/replicate-1/remapping-2/depth.tsv
Converted with header: /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_PCR_NC_2/replicate-1/remapping-2/depth.txt → /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_PCR_NC_2/replicate-1/remapping-2/depth.tsv

In [17]:
##merge rep 1 and rep 2 depth files for each sample
# root = Path("/Users/asjaeger/Desktop/project_source/hpai-PA/seq/data")

for sample_dir in root.iterdir():
    if not sample_dir.is_dir():
        continue

    dfs = []

    for cov_file in sample_dir.rglob("remapping-2/depth.tsv"):
        # Expect: sample/replicate-X/remap/coverage.tsv
        try:
            rep = cov_file.parents[1].name
        except IndexError:
            continue

        df = pd.read_csv(cov_file, sep="\t")
        df["rep"] = rep
        dfs.append(df)

    if not dfs:
        continue

    merged = pd.concat(dfs, ignore_index=True)

    out_file = sample_dir / "depth-reps.tsv"
    merged.to_csv(out_file, sep="\t", index=False)

    print(f"Wrote {out_file}")

Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_4/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run4_RT_NC_1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cl_c2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_5/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm4/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/rt_nc_run9/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC4_run9/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com4/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/rt_nc3_run10/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_PCR_NC_1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run4_PCR_NC_1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com5/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_RT_NC_1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cb_com1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCR_NC1_run9/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_com1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com4/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC3_run9/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com5/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/gn_lbm1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/RTNC2_run8/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC2_run8/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm5/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_lbm1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm4/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/rt_nc2_run10/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_lbm1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/pcr_nc4_run10/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCRNC1_run8/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_6/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cl_c1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_PCR_NC_1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_PCR_NC_2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run4_PCR_NC_2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm10/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com7/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/pcr_nc2_run10/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/pcr_nc2_run9/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/d_com1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm11/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run4_PCR_NC_4/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_PCR_NC_4/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run5_PCR_NC_3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run4_PCR_NC_3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com6/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/kc_com8/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/g_com2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cb_com2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_com1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cb_com3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/cb_com4/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_com6/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/ckr_lbm1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/PCR_NC1_run10/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm6/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_RT_NC_2/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm1/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm8/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm9/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/pcr_nc3_run10/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/run6_RT_NC_3/depth-reps.tsv
Wrote /Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/c_lbm7/depth-reps.tsv

In [18]:
gene_lengths = pd.Series({
    "ha": 1776,
    "mp": 1027,
    "na": 1457,
    "np": 1565,
    "ns": 890,
    "pa": 2233,
    "pb1": 2341,
    "pb2": 2341,
})

In [19]:
##turning into function:

def coverage_pct_per_gene(sample_dir):
    df = pd.read_csv(
        Path(sample_dir) / "depth-reps.tsv",
        sep="\t"
    )

    df = (
        df
        .assign(rep=df["rep"].str.replace("replicate-", "rep"))
        .pivot(index=["gene", "pos"], columns="rep", values="cvg")
        .rename(columns=lambda c: f"cvg_{c}")
        .reset_index()
    )
    # ensure both replicates exist
    if not {"cvg_rep1", "cvg_rep2"}.issubset(df.columns):
        raise ValueError("Missing one or more replicates")

    # filter to >=100X in both replicates
    df = df[
        (df["cvg_rep1"] >= 100) &
        (df["cvg_rep2"] >= 100)
    ]

    observed = df["gene"].value_counts()

    pct = (observed / gene_lengths).fillna(0)

    return pct.to_dict()

In [20]:
##for looping through:

coverage_dict = {}

for sample_dir in root.iterdir():
    if not sample_dir.is_dir():
        continue

    try:
        coverage_dict[sample_dir.name] = coverage_pct_per_gene(sample_dir)
    except (FileNotFoundError, ValueError) as e:
        print(f"Skipping {sample_dir.name}: {e}")
##print statements mostly confirm that NCs and reference files aren't being used here in the loop

Skipping run6_PCR_NC_4: Missing one or more replicates
Skipping run4_RT_NC_1: Missing one or more replicates
Skipping run6_PCR_NC_3: Missing one or more replicates
Skipping cl_c2: Missing one or more replicates
Skipping run6_PCR_NC_2: Missing one or more replicates
Skipping run6_PCR_NC_5: Missing one or more replicates
Skipping rt_nc_run9: Missing one or more replicates
Skipping PCRNC4_run9: Missing one or more replicates
Skipping rt_nc3_run10: Missing one or more replicates
Skipping run5_PCR_NC_1: Missing one or more replicates
Skipping run4_PCR_NC_1: Missing one or more replicates
Skipping run5_RT_NC_1: Missing one or more replicates
Skipping PCR_NC1_run9: Missing one or more replicates
Skipping PCRNC3_run9: Missing one or more replicates
Skipping protein: [Errno 2] No such file or directory: '/Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/protein/depth-reps.tsv'
Skipping RTNC2_run8: Missing one or more replicates
Skipping PCRNC2_run8: Missing one or more replicates
Skipping c_lbm4: Missing one or more replicates
Skipping rt_nc2_run10: Missing one or more replicates
Skipping pcr_nc4_run10: Missing one or more replicates
Skipping PCRNC1_run8: Missing one or more replicates
Skipping run6_PCR_NC_6: Missing one or more replicates
Skipping cl_c1: Missing one or more replicates
Skipping run6_PCR_NC_1: Missing one or more replicates
Skipping run5_PCR_NC_2: Missing one or more replicates
Skipping run4_PCR_NC_2: Missing one or more replicates
Skipping pcr_nc2_run10: Missing one or more replicates
Skipping pcr_nc2_run9: Missing one or more replicates
Skipping run4_PCR_NC_4: Missing one or more replicates
Skipping run5_PCR_NC_4: Missing one or more replicates
Skipping run5_PCR_NC_3: Missing one or more replicates
Skipping run4_PCR_NC_3: Missing one or more replicates
Skipping PCR_NC1_run10: Missing one or more replicates
Skipping run6_RT_NC_2: Missing one or more replicates
Skipping reference: [Errno 2] No such file or directory: '/Users/asjaeger/Desktop/project_source/hpai-PA/hpai-comm-pa/all_com_analysis_2pct/data/reference/depth-reps.tsv'
Skipping pcr_nc3_run10: Missing one or more replicates
Skipping run6_RT_NC_3: Missing one or more replicates

In [21]:
coverage_dict

{'d_lbm2': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.8126286890871655,
  'np': 0.9731629392971246,
  'ns': 1.0,
  'pa': 0.5638154948499776,
  'pb1': 1.0,
  'pb2': 0.5296881674498077},
 'd_lbm3': {'ha': 1.0,
  'mp': 0.022395326192794548,
  'na': 1.0,
  'np': 0.9808306709265175,
  'ns': 1.0,
  'pa': 0.5642633228840125,
  'pb1': 1.0,
  'pb2': 1.0},
 'd_lbm4': {'ha': 1.0,
  'mp': 0.9707887049659202,
  'na': 0.9958819492107069,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 0.9973130317957905,
  'pb1': 1.0,
  'pb2': 0.9953011533532679},
 'kc_com3': {'ha': 1.0,
  'mp': 0.9084712755598832,
  'na': 1.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'kc_com4': {'ha': 1.0,
  'mp': 0.9191820837390458,
  'na': 1.0,
  'np': 0.9936102236421726,
  'ns': 1.0,
  'pa': 0.999552171965965,
  'pb1': 1.0,
  'pb2': 0.99017513882956},
 'd_com3': {'ha': 1.0,
  'mp': 0.029211295034079845,
  'na': 0.9450926561427591,
  'np': 0.0,
  'ns': 1.0,
  'pa': 0.5409762651141962,
  'pb1': 0.6398974797095258,
  'pb2': 0.9982913284920973},
 'kc_com5': {'ha': 1.0,
  'mp': 0.937682570593963,
  'na': 0.9993136582017845,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9914566424604869},
 'kc_com2': {'ha': 1.0,
  'mp': 0.9464459591041869,
  'na': 1.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 0.6330627936779154,
  'pb2': 1.0},
 'd_com2': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.9450926561427591,
  'np': 0.9808306709265175,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'cb_com1': {'ha': 1.0,
  'mp': 0.9688412852969815,
  'na': 0.9897048730267674,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'c_com3': {'ha': 0.5884009009009009,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.0,
  'ns': 0.3202247191011236,
  'pa': 0.5642633228840125,
  'pb1': 0.46304997864160613,
  'pb2': 0.5296881674498077},
 'g_com1': {'ha': 1.0,
  'mp': 0.06426484907497566,
  'na': 0.0,
  'np': 0.0,
  'ns': 1.0,
  'pa': 0.5060456784594716,
  'pb1': 0.0,
  'pb2': 0.5305425032037591},
 'c_com4': {'ha': 0.0,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.0,
  'ns': 0.0,
  'pa': 0.0,
  'pb1': 0.0,
  'pb2': 0.0},
 'ckr_com3': {'ha': 1.0,
  'mp': 0.875365141187926,
  'na': 0.9444063143445436,
  'np': 0.9814696485623003,
  'ns': 0.996629213483146,
  'pa': 0.999552171965965,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_com5': {'ha': 1.0,
  'mp': 0.9415774099318404,
  'na': 1.0,
  'np': 0.9968051118210862,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_com2': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.9052848318462594,
  'np': 0.4325878594249201,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'ckr_com2': {'ha': 1.0,
  'mp': 0.9776046738072055,
  'na': 0.9450926561427591,
  'np': 0.9968051118210862,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'gn_lbm1': {'ha': 1.0,
  'mp': 0.943524829600779,
  'na': 1.0,
  'np': 0.9827476038338658,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_lbm2': {'ha': 0.9977477477477478,
  'mp': 0.035053554040895815,
  'na': 0.9402882635552505,
  'np': 0.9539936102236422,
  'ns': 1.0,
  'pa': 0.5638154948499776,
  'pb1': 1.0,
  'pb2': 0.9850491243058522},
 'c_lbm5': {'ha': 1.0,
  'mp': 0.9513145082765336,
  'na': 1.0,
  'np': 0.9923322683706071,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'g_lbm1': {'ha': 0.9994369369369369,
  'mp': 0.0,
  'na': 0.9080301990391215,
  'np': 0.014696485623003195,
  'ns': 0.9943820224719101,
  'pa': 0.5642633228840125,
  'pb1': 1.0,
  'pb2': 0.4527979495941905},
 'c_lbm3': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.09584664536741214,
  'ns': 1.0,
  'pa': 0.5638154948499776,
  'pb1': 0.9995728321230244,
  'pb2': 0.6253737718923537},
 'd_lbm1': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 0.5638154948499776,
  'pb1': 1.0,
  'pb2': 0.5313968389577104},
 'c_lbm10': {'ha': 1.0,
  'mp': 0.9503407984420643,
  'na': 1.0,
  'np': 0.9929712460063898,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'kc_com7': {'ha': 1.0,
  'mp': 0.0,
  'na': 1.0,
  'np': 0.853035143769968,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 0.7103801794105084,
  'pb2': 0.5322511747116617},
 'd_com1': {'ha': 1.0,
  'mp': 0.9113924050632911,
  'na': 0.9444063143445436,
  'np': 0.9865814696485623,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_lbm11': {'ha': 0.9971846846846847,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.0,
  'ns': 0.9943820224719101,
  'pa': 0.5638154948499776,
  'pb1': 0.9696710807347287,
  'pb2': 0.0},
 'kc_com1': {'ha': 1.0,
  'mp': 0.9396299902629016,
  'na': 1.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 0.999552171965965,
  'pb1': 1.0,
  'pb2': 1.0},
 'kc_com6': {'ha': 1.0,
  'mp': 0.17429406037000975,
  'na': 1.0,
  'np': 0.9808306709265175,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.5326783425886373},
 'kc_com8': {'ha': 1.0,
  'mp': 0.03213242453748783,
  'na': 0.9993136582017845,
  'np': 0.9763578274760384,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.5322511747116617},
 'g_com2': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.8435140700068634,
  'np': 0.0,
  'ns': 1.0,
  'pa': 0.9449171518137035,
  'pb1': 0.0,
  'pb2': 0.5322511747116617},
 'cb_com2': {'ha': 1.0,
  'mp': 0.9425511197663097,
  'na': 1.0,
  'np': 0.9968051118210862,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'ckr_com1': {'ha': 1.0,
  'mp': 0.9328140214216164,
  'na': 0.9450926561427591,
  'np': 0.9827476038338658,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'cb_com3': {'ha': 1.0,
  'mp': 0.5404089581304771,
  'na': 1.0,
  'np': 0.9757188498402556,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9923109782144383},
 'c_com1': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.0,
  'ns': 0.9977528089887641,
  'pa': 0.9973130317957905,
  'pb1': 0.46817599316531394,
  'pb2': 0.5151644596326356},
 'cb_com4': {'ha': 1.0,
  'mp': 0.006815968841285297,
  'na': 1.0,
  'np': 0.9565495207667731,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.981631781290047},
 'c_com6': {'ha': 1.0,
  'mp': 0.9250243427458618,
  'na': 1.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'ckr_lbm1': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.20727522306108442,
  'np': 0.929073482428115,
  'ns': 1.0,
  'pa': 0.5633676668159426,
  'pb1': 1.0,
  'pb2': 0.9034600598035027},
 'c_lbm6': {'ha': 1.0,
  'mp': 0.0,
  'na': 1.0,
  'np': 0.9642172523961662,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'c_lbm1': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.9993136582017845,
  'np': 0.979552715654952,
  'ns': 0.998876404494382,
  'pa': 0.9973130317957905,
  'pb1': 1.0,
  'pb2': 0.5805211448099103},
 'c_lbm8': {'ha': 1.0,
  'mp': 0.0,
  'na': 1.0,
  'np': 0.9808306709265175,
  'ns': 1.0,
  'pa': 0.9973130317957905,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_lbm9': {'ha': 1.0,
  'mp': 0.3661148977604674,
  'na': 0.9993136582017845,
  'np': 0.9814696485623003,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'c_lbm7': {'ha': 1.0,
  'mp': 0.16747809152872445,
  'na': 1.0,
  'np': 0.9814696485623003,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0}}

In [22]:
# Multiply values by gene lengths
sample_cvg_nt = {
    sample: {gene: value * gene_lengths[gene] for gene, value in genes.items()}
    for sample, genes in coverage_dict.items()
}

# Optionally, convert to integers if you want nucleotide counts
sample_cvg_nt_int = {
    sample: {gene: int(round(value)) for gene, value in genes.items()}
    for sample, genes in sample_cvg_nt.items()
}

print(sample_cvg_nt_int)

{'d_lbm2': {'ha': 1776, 'mp': 0, 'na': 1184, 'np': 1523, 'ns': 890, 'pa': 1259, 'pb1': 2341, 'pb2': 1240}, 'd_lbm3': {'ha': 1776, 'mp': 23, 'na': 1457, 'np': 1535, 'ns': 890, 'pa': 1260, 'pb1': 2341, 'pb2': 2341}, 'd_lbm4': {'ha': 1776, 'mp': 997, 'na': 1451, 'np': 1564, 'ns': 890, 'pa': 2227, 'pb1': 2341, 'pb2': 2330}, 'kc_com3': {'ha': 1776, 'mp': 933, 'na': 1457, 'np': 1564, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2341}, 'kc_com4': {'ha': 1776, 'mp': 944, 'na': 1457, 'np': 1555, 'ns': 890, 'pa': 2232, 'pb1': 2341, 'pb2': 2318}, 'd_com3': {'ha': 1776, 'mp': 30, 'na': 1377, 'np': 0, 'ns': 890, 'pa': 1208, 'pb1': 1498, 'pb2': 2337}, 'kc_com5': {'ha': 1776, 'mp': 963, 'na': 1456, 'np': 1564, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2321}, 'kc_com2': {'ha': 1776, 'mp': 972, 'na': 1457, 'np': 1564, 'ns': 890, 'pa': 2233, 'pb1': 1482, 'pb2': 2341}, 'd_com2': {'ha': 1776, 'mp': 0, 'na': 1377, 'np': 1535, 'ns': 889, 'pa': 2233, 'pb1': 2341, 'pb2': 2340}, 'cb_com1': {'ha': 1776, 'mp': 995, 'na': 1442, 'np': 1564, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2341}, 'c_com3': {'ha': 1045, 'mp': 0, 'na': 0, 'np': 0, 'ns': 285, 'pa': 1260, 'pb1': 1084, 'pb2': 1240}, 'g_com1': {'ha': 1776, 'mp': 66, 'na': 0, 'np': 0, 'ns': 890, 'pa': 1130, 'pb1': 0, 'pb2': 1242}, 'c_com4': {'ha': 0, 'mp': 0, 'na': 0, 'np': 0, 'ns': 0, 'pa': 0, 'pb1': 0, 'pb2': 0}, 'ckr_com3': {'ha': 1776, 'mp': 899, 'na': 1376, 'np': 1536, 'ns': 887, 'pa': 2232, 'pb1': 2341, 'pb2': 2340}, 'c_com5': {'ha': 1776, 'mp': 967, 'na': 1457, 'np': 1560, 'ns': 889, 'pa': 2233, 'pb1': 2341, 'pb2': 2340}, 'c_com2': {'ha': 1776, 'mp': 0, 'na': 1319, 'np': 677, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2341}, 'ckr_com2': {'ha': 1776, 'mp': 1004, 'na': 1377, 'np': 1560, 'ns': 889, 'pa': 2233, 'pb1': 2341, 'pb2': 2340}, 'gn_lbm1': {'ha': 1776, 'mp': 969, 'na': 1457, 'np': 1538, 'ns': 889, 'pa': 2233, 'pb1': 2341, 'pb2': 2340}, 'c_lbm2': {'ha': 1772, 'mp': 36, 'na': 1370, 'np': 1493, 'ns': 890, 'pa': 1259, 'pb1': 2341, 'pb2': 2306}, 'c_lbm5': {'ha': 1776, 'mp': 977, 'na': 1457, 'np': 1553, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2341}, 'g_lbm1': {'ha': 1775, 'mp': 0, 'na': 1323, 'np': 23, 'ns': 885, 'pa': 1260, 'pb1': 2341, 'pb2': 1060}, 'c_lbm3': {'ha': 1776, 'mp': 0, 'na': 0, 'np': 150, 'ns': 890, 'pa': 1259, 'pb1': 2340, 'pb2': 1464}, 'd_lbm1': {'ha': 1776, 'mp': 0, 'na': 0, 'np': 1564, 'ns': 890, 'pa': 1259, 'pb1': 2341, 'pb2': 1244}, 'c_lbm10': {'ha': 1776, 'mp': 976, 'na': 1457, 'np': 1554, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2341}, 'kc_com7': {'ha': 1776, 'mp': 0, 'na': 1457, 'np': 1335, 'ns': 890, 'pa': 2233, 'pb1': 1663, 'pb2': 1246}, 'd_com1': {'ha': 1776, 'mp': 936, 'na': 1376, 'np': 1544, 'ns': 889, 'pa': 2233, 'pb1': 2341, 'pb2': 2340}, 'c_lbm11': {'ha': 1771, 'mp': 0, 'na': 0, 'np': 0, 'ns': 885, 'pa': 1259, 'pb1': 2270, 'pb2': 0}, 'kc_com1': {'ha': 1776, 'mp': 965, 'na': 1457, 'np': 1564, 'ns': 890, 'pa': 2232, 'pb1': 2341, 'pb2': 2341}, 'kc_com6': {'ha': 1776, 'mp': 179, 'na': 1457, 'np': 1535, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 1247}, 'kc_com8': {'ha': 1776, 'mp': 33, 'na': 1456, 'np': 1528, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 1246}, 'g_com2': {'ha': 1776, 'mp': 0, 'na': 1229, 'np': 0, 'ns': 890, 'pa': 2110, 'pb1': 0, 'pb2': 1246}, 'cb_com2': {'ha': 1776, 'mp': 968, 'na': 1457, 'np': 1560, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2340}, 'ckr_com1': {'ha': 1776, 'mp': 958, 'na': 1377, 'np': 1538, 'ns': 889, 'pa': 2233, 'pb1': 2341, 'pb2': 2340}, 'cb_com3': {'ha': 1776, 'mp': 555, 'na': 1457, 'np': 1527, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2323}, 'c_com1': {'ha': 1776, 'mp': 0, 'na': 0, 'np': 0, 'ns': 888, 'pa': 2227, 'pb1': 1096, 'pb2': 1206}, 'cb_com4': {'ha': 1776, 'mp': 7, 'na': 1457, 'np': 1497, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2298}, 'c_com6': {'ha': 1776, 'mp': 950, 'na': 1457, 'np': 1564, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2340}, 'ckr_lbm1': {'ha': 1776, 'mp': 0, 'na': 302, 'np': 1454, 'ns': 890, 'pa': 1258, 'pb1': 2341, 'pb2': 2115}, 'c_lbm6': {'ha': 1776, 'mp': 0, 'na': 1457, 'np': 1509, 'ns': 889, 'pa': 2233, 'pb1': 2341, 'pb2': 2341}, 'c_lbm1': {'ha': 1776, 'mp': 0, 'na': 1456, 'np': 1533, 'ns': 889, 'pa': 2227, 'pb1': 2341, 'pb2': 1359}, 'c_lbm8': {'ha': 1776, 'mp': 0, 'na': 1457, 'np': 1535, 'ns': 890, 'pa': 2227, 'pb1': 2341, 'pb2': 2340}, 'c_lbm9': {'ha': 1776, 'mp': 376, 'na': 1456, 'np': 1536, 'ns': 890, 'pa': 2233, 'pb1': 2341, 'pb2': 2341}, 'c_lbm7': {'ha': 1776, 'mp': 172, 'na': 1457, 'np': 1536, 'ns': 889, 'pa': 2233, 'pb1': 2341, 'pb2': 2341}}

In [9]:
#export coverage dict
import json

with open("../all_com_analysis_2pct/data/sample_cvg_nt.json", "w") as f:
    json.dump(coverage_dict, f, indent=2)

In [3]:
##read in aa cvgs, from permutation script
import json

# with open("../../aa_cvg_test.json") as f:
with open("../all_com_analysis_2pct/data/allcom_cvg.json") as f:

    aa_cvg = json.load(f)
aa_cvg

{'c_com5': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_com6': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm10': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm11': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm1': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm2': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm3': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm5': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm6': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm7': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm8': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'c_lbm9': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'cb_com1': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'cb_com2': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'cb_com3': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'cb_com4': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'ckr_com1': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'ckr_com2': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'ckr_com3': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'd_com1': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'd_com2': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'd_com3': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'd_lbm1': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'd_lbm2': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'd_lbm3': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'd_lbm4': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'g_com1': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'g_com2': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'g_lbm1': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'gn_lbm1': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'kc_com3': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'kc_com4': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'kc_com5': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'kc_com6': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'kc_com7': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279},
 'kc_com8': {'PB2': 760,
  'PB1': 758,
  'PA': 717,
  'HA': 568,
  'NP': 499,
  'NA': 470,
  'M1': 253,
  'M2': 327,
  'NS1': 231,
  'NEP': 279}}

In [4]:
##read in coverage_dict if already produced

# with open("../../aa_cvg_test.json") as f:
with open("../../seq/all_com_analysis/data/sample_cvg.json") as f:

    coverage_dict = json.load(f)
coverage_dict

{'d_lbm2': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.8126286890871655,
  'np': 0.9731629392971246,
  'ns': 1.0,
  'pa': 0.5638154948499776,
  'pb1': 1.0,
  'pb2': 0.5296881674498077},
 'd_lbm3': {'ha': 1.0,
  'mp': 0.022395326192794548,
  'na': 1.0,
  'np': 0.9808306709265175,
  'ns': 1.0,
  'pa': 0.5642633228840125,
  'pb1': 1.0,
  'pb2': 1.0},
 'd_lbm4': {'ha': 1.0,
  'mp': 0.9707887049659202,
  'na': 0.9958819492107069,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 0.9973130317957905,
  'pb1': 1.0,
  'pb2': 0.9953011533532679},
 'kc_com3': {'ha': 1.0,
  'mp': 0.9084712755598832,
  'na': 1.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'kc_com4': {'ha': 1.0,
  'mp': 0.9191820837390458,
  'na': 1.0,
  'np': 0.9936102236421726,
  'ns': 1.0,
  'pa': 0.999552171965965,
  'pb1': 1.0,
  'pb2': 0.99017513882956},
 'd_com3': {'ha': 1.0,
  'mp': 0.029211295034079845,
  'na': 0.9450926561427591,
  'np': 0.0,
  'ns': 1.0,
  'pa': 0.5409762651141962,
  'pb1': 0.6398974797095258,
  'pb2': 0.9982913284920973},
 'kc_com5': {'ha': 1.0,
  'mp': 0.937682570593963,
  'na': 0.9993136582017845,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9914566424604869},
 'kc_com2': {'ha': 1.0,
  'mp': 0.9464459591041869,
  'na': 1.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 0.6330627936779154,
  'pb2': 1.0},
 'd_com2': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.9450926561427591,
  'np': 0.9808306709265175,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'cb_com1': {'ha': 1.0,
  'mp': 0.9688412852969815,
  'na': 0.9897048730267674,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'c_com3': {'ha': 0.5884009009009009,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.0,
  'ns': 0.3202247191011236,
  'pa': 0.5620241827138379,
  'pb1': 0.46304997864160613,
  'pb2': 0.5296881674498077},
 'g_com1': {'ha': 1.0,
  'mp': 0.06426484907497566,
  'na': 0.0,
  'np': 0.0,
  'ns': 1.0,
  'pa': 0.5060456784594716,
  'pb1': 0.0,
  'pb2': 0.5305425032037591},
 'c_com4': {'ha': 0.0,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.0,
  'ns': 0.0,
  'pa': 0.0,
  'pb1': 0.0,
  'pb2': 0.0},
 'ckr_com3': {'ha': 1.0,
  'mp': 0.875365141187926,
  'na': 0.9444063143445436,
  'np': 0.9814696485623003,
  'ns': 0.996629213483146,
  'pa': 0.999552171965965,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_com5': {'ha': 1.0,
  'mp': 0.9415774099318404,
  'na': 1.0,
  'np': 0.9968051118210862,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_com2': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.9052848318462594,
  'np': 0.4325878594249201,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'ckr_com2': {'ha': 1.0,
  'mp': 0.9776046738072055,
  'na': 0.9450926561427591,
  'np': 0.9968051118210862,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'gn_lbm1': {'ha': 1.0,
  'mp': 0.943524829600779,
  'na': 1.0,
  'np': 0.9827476038338658,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_lbm2': {'ha': 0.9977477477477478,
  'mp': 0.035053554040895815,
  'na': 0.9402882635552505,
  'np': 0.9539936102236422,
  'ns': 1.0,
  'pa': 0.5638154948499776,
  'pb1': 1.0,
  'pb2': 0.9850491243058522},
 'c_lbm5': {'ha': 1.0,
  'mp': 0.9513145082765336,
  'na': 1.0,
  'np': 0.9923322683706071,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'g_lbm1': {'ha': 0.9994369369369369,
  'mp': 0.0,
  'na': 0.9080301990391215,
  'np': 0.014696485623003195,
  'ns': 0.9943820224719101,
  'pa': 0.5642633228840125,
  'pb1': 1.0,
  'pb2': 0.4527979495941905},
 'c_lbm3': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.09584664536741214,
  'ns': 1.0,
  'pa': 0.5638154948499776,
  'pb1': 0.9995728321230244,
  'pb2': 0.6253737718923537},
 'd_lbm1': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 0.5638154948499776,
  'pb1': 1.0,
  'pb2': 0.5313968389577104},
 'c_lbm10': {'ha': 1.0,
  'mp': 0.9503407984420643,
  'na': 1.0,
  'np': 0.9929712460063898,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'kc_com7': {'ha': 1.0,
  'mp': 0.0,
  'na': 1.0,
  'np': 0.853035143769968,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 0.7103801794105084,
  'pb2': 0.5322511747116617},
 'd_com1': {'ha': 1.0,
  'mp': 0.9113924050632911,
  'na': 0.9444063143445436,
  'np': 0.9865814696485623,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_lbm11': {'ha': 0.9971846846846847,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.0,
  'ns': 0.9943820224719101,
  'pa': 0.5638154948499776,
  'pb1': 0.9696710807347287,
  'pb2': 0.0},
 'kc_com1': {'ha': 1.0,
  'mp': 0.9396299902629016,
  'na': 1.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 0.999552171965965,
  'pb1': 1.0,
  'pb2': 1.0},
 'kc_com6': {'ha': 1.0,
  'mp': 0.17429406037000975,
  'na': 1.0,
  'np': 0.9808306709265175,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.5326783425886373},
 'kc_com8': {'ha': 1.0,
  'mp': 0.03213242453748783,
  'na': 0.9993136582017845,
  'np': 0.9763578274760384,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.5322511747116617},
 'g_com2': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.8435140700068634,
  'np': 0.0,
  'ns': 1.0,
  'pa': 0.9449171518137035,
  'pb1': 0.0,
  'pb2': 0.5322511747116617},
 'cb_com2': {'ha': 1.0,
  'mp': 0.9425511197663097,
  'na': 1.0,
  'np': 0.9968051118210862,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'ckr_com1': {'ha': 1.0,
  'mp': 0.9328140214216164,
  'na': 0.9450926561427591,
  'np': 0.9827476038338658,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'cb_com3': {'ha': 1.0,
  'mp': 0.5404089581304771,
  'na': 1.0,
  'np': 0.9757188498402556,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9923109782144383},
 'c_com1': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.0,
  'np': 0.0,
  'ns': 0.9977528089887641,
  'pa': 0.5696372592924317,
  'pb1': 0.46817599316531394,
  'pb2': 0.5151644596326356},
 'cb_com4': {'ha': 1.0,
  'mp': 0.006815968841285297,
  'na': 1.0,
  'np': 0.9565495207667731,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.981631781290047},
 'c_com6': {'ha': 1.0,
  'mp': 0.9250243427458618,
  'na': 1.0,
  'np': 0.9993610223642172,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'ckr_lbm1': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.20727522306108442,
  'np': 0.929073482428115,
  'ns': 1.0,
  'pa': 0.5633676668159426,
  'pb1': 1.0,
  'pb2': 0.9034600598035027},
 'c_lbm6': {'ha': 1.0,
  'mp': 0.0,
  'na': 1.0,
  'np': 0.9642172523961662,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'c_lbm1': {'ha': 1.0,
  'mp': 0.0,
  'na': 0.9993136582017845,
  'np': 0.979552715654952,
  'ns': 0.998876404494382,
  'pa': 0.9973130317957905,
  'pb1': 1.0,
  'pb2': 0.5805211448099103},
 'c_lbm8': {'ha': 1.0,
  'mp': 0.0,
  'na': 1.0,
  'np': 0.9808306709265175,
  'ns': 1.0,
  'pa': 0.9973130317957905,
  'pb1': 1.0,
  'pb2': 0.9995728321230244},
 'c_lbm9': {'ha': 1.0,
  'mp': 0.3661148977604674,
  'na': 0.9993136582017845,
  'np': 0.9814696485623003,
  'ns': 1.0,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0},
 'c_lbm7': {'ha': 1.0,
  'mp': 0.16747809152872445,
  'na': 1.0,
  'np': 0.9814696485623003,
  'ns': 0.998876404494382,
  'pa': 1.0,
  'pb1': 1.0,
  'pb2': 1.0}}

In [23]:
gene_map = {
    "HA": "ha",
    "NA": "na",
    "NP": "np",
    "PA": "pa",
    "PB1": "pb1",
    "PB2": "pb2",
    "NS1": "ns",
    "NEP": "ns",
    "M1": "mp",
    "M2": "mp",
}

# count_dict → what’s there, subset here!

# coverage_dict → the fraction that has coverage dict made here

# gene_map → how names correspond

# sample_cvg → QC-adjusted result

sample_cvg = {}

for sample, counts in aa_cvg.items():
    if sample not in coverage_dict:
        continue

    sample_cvg[sample] = {}

    for gene, count in counts.items():
        gene_upper = gene.upper()

        if gene_upper not in gene_map:
            continue

        cov_key = gene_map[gene_upper]

        cov_frac = coverage_dict[sample].get(cov_key, 0)

        sample_cvg[sample][gene_upper] = cov_frac * count
sample_cvg

{'c_com5': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 497.405750798722,
  'NA': 470.0,
  'M1': 238.2190847127556,
  'M2': 307.8958130477118,
  'NS1': 230.74044943820223,
  'NEP': 278.6865168539326},
 'c_com6': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 498.6811501597444,
  'NA': 470.0,
  'M1': 234.03115871470303,
  'M2': 302.4829600778968,
  'NS1': 231.0,
  'NEP': 279.0},
 'c_lbm10': {'PB2': 760.0,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 495.49265175718847,
  'NA': 470.0,
  'M1': 240.43622200584227,
  'M2': 310.761441090555,
  'NS1': 231.0,
  'NEP': 279.0},
 'c_lbm11': {'PB2': 0.0,
  'PB1': 735.0106791969243,
  'PA': 404.25570980743396,
  'HA': 566.4009009009009,
  'NP': 0.0,
  'NA': 0.0,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 229.70224719101122,
  'NEP': 277.4325842696629},
 'c_lbm1': {'PB2': 441.1960700555319,
  'PB1': 758.0,
  'PA': 715.0734437975817,
  'HA': 568.0,
  'NP': 488.7968051118211,
  'NA': 469.6774193548387,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 230.74044943820223,
  'NEP': 278.6865168539326},
 'c_lbm2': {'PB2': 748.6373344724477,
  'PB1': 758.0,
  'PA': 404.25570980743396,
  'HA': 566.7207207207207,
  'NP': 476.04281150159744,
  'NA': 441.93548387096774,
  'M1': 8.868549172346642,
  'M2': 11.462512171372932,
  'NS1': 231.0,
  'NEP': 279.0},
 'c_lbm3': {'PB2': 475.2840666381888,
  'PB1': 757.6762067492525,
  'PA': 404.25570980743396,
  'HA': 568.0,
  'NP': 47.82747603833866,
  'NA': 0.0,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 231.0,
  'NEP': 279.0},
 'c_lbm5': {'PB2': 760.0,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 495.1738019169329,
  'NA': 470.0,
  'M1': 240.68257059396302,
  'M2': 311.0798442064265,
  'NS1': 231.0,
  'NEP': 279.0},
 'c_lbm6': {'PB2': 760.0,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 481.1444089456869,
  'NA': 470.0,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 230.74044943820223,
  'NEP': 278.6865168539326},
 'c_lbm7': {'PB2': 760.0,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 489.7533546325879,
  'NA': 470.0,
  'M1': 42.37195715676729,
  'M2': 54.76533592989289,
  'NS1': 230.74044943820223,
  'NEP': 278.6865168539326},
 'c_lbm8': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 715.0734437975817,
  'HA': 568.0,
  'NP': 489.43450479233223,
  'NA': 470.0,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 231.0,
  'NEP': 279.0},
 'c_lbm9': {'PB2': 760.0,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 489.7533546325879,
  'NA': 469.6774193548387,
  'M1': 92.62706913339825,
  'M2': 119.71957156767284,
  'NS1': 231.0,
  'NEP': 279.0},
 'cb_com1': {'PB2': 760.0,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 498.6811501597444,
  'NA': 465.16129032258067,
  'M1': 245.11684518013632,
  'M2': 316.81110029211294,
  'NS1': 231.0,
  'NEP': 279.0},
 'cb_com2': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 497.405750798722,
  'NA': 470.0,
  'M1': 238.46543330087636,
  'M2': 308.2142161635833,
  'NS1': 231.0,
  'NEP': 279.0},
 'cb_com3': {'PB2': 754.156343442973,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 486.88370607028753,
  'NA': 470.0,
  'M1': 136.7234664070107,
  'M2': 176.713729308666,
  'NS1': 231.0,
  'NEP': 279.0},
 'cb_com4': {'PB2': 746.0401537804357,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 477.31821086261976,
  'NA': 470.0,
  'M1': 1.7244401168451802,
  'M2': 2.228821811100292,
  'NS1': 231.0,
  'NEP': 279.0},
 'ckr_com1': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 490.39105431309906,
  'NA': 444.19354838709677,
  'M1': 236.00194741966894,
  'M2': 305.03018500486854,
  'NS1': 230.74044943820223,
  'NEP': 278.6865168539326},
 'ckr_com2': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 497.405750798722,
  'NA': 444.19354838709677,
  'M1': 247.333982473223,
  'M2': 319.6767283349562,
  'NS1': 230.74044943820223,
  'NEP': 278.6865168539326},
 'ckr_com3': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 716.678907299597,
  'HA': 568.0,
  'NP': 489.7533546325879,
  'NA': 443.8709677419355,
  'M1': 221.46738072054526,
  'M2': 286.2444011684518,
  'NS1': 230.22134831460673,
  'NEP': 278.0595505617977},
 'd_com1': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 492.3041533546326,
  'NA': 443.8709677419355,
  'M1': 230.58227848101265,
  'M2': 298.0253164556962,
  'NS1': 230.74044943820223,
  'NEP': 278.6865168539326},
 'd_com2': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 489.43450479233223,
  'NA': 444.19354838709677,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 230.74044943820223,
  'NEP': 278.6865168539326},
 'd_com3': {'PB2': 758.701409653994,
  'PB1': 485.04228961982056,
  'PA': 387.87998208687867,
  'HA': 568.0,
  'NP': 0.0,
  'NA': 444.19354838709677,
  'M1': 7.3904576436222005,
  'M2': 9.55209347614411,
  'NS1': 231.0,
  'NEP': 279.0},
 'd_lbm1': {'PB2': 403.8615976078599,
  'PB1': 758.0,
  'PA': 404.25570980743396,
  'HA': 568.0,
  'NP': 498.6811501597444,
  'NA': 0.0,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 231.0,
  'NEP': 279.0},
 'd_lbm2': {'PB2': 402.5630072618539,
  'PB1': 758.0,
  'PA': 404.25570980743396,
  'HA': 568.0,
  'NP': 485.6083067092652,
  'NA': 381.93548387096774,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 231.0,
  'NEP': 279.0},
 'd_lbm3': {'PB2': 760.0,
  'PB1': 758.0,
  'PA': 404.57680250783693,
  'HA': 568.0,
  'NP': 489.43450479233223,
  'NA': 470.0,
  'M1': 5.66601752677702,
  'M2': 7.323271665043817,
  'NS1': 231.0,
  'NEP': 279.0},
 'd_lbm4': {'PB2': 756.4288765484836,
  'PB1': 758.0,
  'PA': 715.0734437975817,
  'HA': 568.0,
  'NP': 498.6811501597444,
  'NA': 468.06451612903226,
  'M1': 245.6095423563778,
  'M2': 317.4479065238559,
  'NS1': 231.0,
  'NEP': 279.0},
 'g_com1': {'PB2': 403.2123024348569,
  'PB1': 0.0,
  'PA': 362.8347514554411,
  'HA': 568.0,
  'NP': 0.0,
  'NA': 0.0,
  'M1': 16.259006815968842,
  'M2': 21.01460564751704,
  'NS1': 231.0,
  'NEP': 279.0},
 'g_com2': {'PB2': 404.5108927808629,
  'PB1': 0.0,
  'PA': 677.5055978504254,
  'HA': 568.0,
  'NP': 0.0,
  'NA': 396.4516129032258,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 231.0,
  'NEP': 279.0},
 'g_lbm1': {'PB2': 344.1264416915848,
  'PB1': 758.0,
  'PA': 404.57680250783693,
  'HA': 567.6801801801802,
  'NP': 7.3335463258785945,
  'NA': 426.77419354838713,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 229.70224719101122,
  'NEP': 277.4325842696629},
 'gn_lbm1': {'PB2': 759.6753524134986,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 490.39105431309906,
  'NA': 470.0,
  'M1': 238.71178188899708,
  'M2': 308.5326192794547,
  'NS1': 230.74044943820223,
  'NEP': 278.6865168539326},
 'kc_com3': {'PB2': 760.0,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 498.6811501597444,
  'NA': 470.0,
  'M1': 229.84323271665045,
  'M2': 297.0701071080818,
  'NS1': 231.0,
  'NEP': 279.0},
 'kc_com4': {'PB2': 752.5331055104656,
  'PB1': 758.0,
  'PA': 716.678907299597,
  'HA': 568.0,
  'NP': 495.8115015974441,
  'NA': 470.0,
  'M1': 232.55306718597856,
  'M2': 300.57254138266796,
  'NS1': 231.0,
  'NEP': 279.0},
 'kc_com5': {'PB2': 753.50704826997,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 498.6811501597444,
  'NA': 469.6774193548387,
  'M1': 237.23369036027265,
  'M2': 306.6222005842259,
  'NS1': 231.0,
  'NEP': 279.0},
 'kc_com6': {'PB2': 404.8355403673644,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 489.43450479233223,
  'NA': 470.0,
  'M1': 44.09639727361247,
  'M2': 56.99415774099319,
  'NS1': 231.0,
  'NEP': 279.0},
 'kc_com7': {'PB2': 404.5108927808629,
  'PB1': 538.4681759931653,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 425.664536741214,
  'NA': 470.0,
  'M1': 0.0,
  'M2': 0.0,
  'NS1': 231.0,
  'NEP': 279.0},
 'kc_com8': {'PB2': 404.5108927808629,
  'PB1': 758.0,
  'PA': 717.0,
  'HA': 568.0,
  'NP': 487.20255591054314,
  'NA': 469.6774193548387,
  'M1': 8.129503407984421,
  'M2': 10.50730282375852,
  'NS1': 231.0,
  'NEP': 279.0}}

In [14]:
##export aa cvg updated
with open("../all_com_analysis_2pct/data/sample_cvg_aa_merged.json", "w") as f:
    json.dump(sample_cvg, f, indent=2)

In [ ]:
##so basically this should work to replace the aa_coverage dicts in the permutations script
##so once i have depth.txts outputting again, can try outputting

In [25]:
df = pd.read_csv('../output_dfs/2026-05-05_repshared_SNVs_allcom_lbm_2pct.tsv', sep='\t')
df['gene'] = df['gene'].fillna('NA')

print(df['gene'].unique())

['NA' 'PA' 'PB1' 'NP' 'PB2' 'HA' 'NS1' 'M2' 'M1' 'NEP']

In [26]:
df

,segment,position,allele,coding_region_change,gene,Frequency_1,Frequency_2,sample,amino_acid,gene_pos,...,ct_value,rep_shared,order,county,date,species,species_group,color,avg_freq,order_domstat
0,na,43,T,Ile8Thr,NA,0.3326,0.3412,c_com5,8,NA_8,...,22.01,shared,galliformes,unknown,2025-01-26,NaN,Galliformes,commercial_nonsynonymous,0.33690,galliformes_commercial
1,na,67,T,Val16Ala,NA,0.2439,0.2890,c_com5,16,NA_16,...,22.01,shared,galliformes,unknown,2025-01-26,NaN,Galliformes,commercial_nonsynonymous,0.26645,galliformes_commercial
2,na,76,T,Ile19Thr,NA,0.2454,0.2615,c_com5,19,NA_19,...,22.01,shared,galliformes,unknown,2025-01-26,NaN,Galliformes,commercial_nonsynonymous,0.25345,galliformes_commercial
3,na,79,T,Ile20Thr,NA,0.2392,0.2624,c_com5,20,NA_20,...,22.01,shared,galliformes,unknown,2025-01-26,NaN,Galliformes,commercial_nonsynonymous,0.25080,galliformes_commercial
4,pa,1173,C,Asp383Asp,PA,0.1338,0.1468,c_com5,383,PA_383,...,22.01,shared,galliformes,unknown,2025-01-26,NaN,Galliformes,commercial_synonymous,0.14030,galliformes_commercial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,pb2,1560,A,Val511Val,PB2,0.0869,0.0918,kc_com6,511,PB2_511,...,21.93,shared,anseriformes,Chester,2023-02-23,duck,Anseriformes,commercial_synonymous,0.08935,anseriformes_commercial
303,pb2,1659,A,Ser544Ser,PB2,0.4205,0.4155,kc_com6,544,PB2_544,...,21.93,shared,anseriformes,Chester,2023-02-23,duck,Anseriformes,commercial_synonymous,0.41800,anseriformes_commercial
304,np,1023,T,Ser326Ser,NP,0.1652,0.0818,kc_com7,326,NP_326,...,22.13,shared,anseriformes,Chester,2023-02-23,duck,Anseriformes,commercial_synonymous,0.12350,anseriformes_commercial
305,pb2,1659,A,Ser544Ser,PB2,0.3472,0.3537,kc_com7,544,PB2_544,...,22.13,shared,anseriformes,Chester,2023-02-23,duck,Anseriformes,commercial_synonymous,0.35045,anseriformes_commercial
306,pb1,1254,T,Gly410Gly,PB1,0.0299,0.0355,kc_com8,410,PB1_410,...,27.29,shared,anseriformes,Lancaster,2023-02-24,duck,Anseriformes,commercial_synonymous,0.03270,anseriformes_commercial

In [27]:
df['segment'].unique()

array(['na', 'pa', 'pb1', 'np', 'pb2', 'ha', 'ns', 'mp'], dtype=object)

In [28]:
import re

SNPs = {}

for index, row in df.iterrows():
    sample = row['sample']
    aa_change = row['coding_region_change']
    syn_status = row['syn_non']
    gene = row['segment']

    # Extract amino acid site number
    match = re.search(r'(\d+)', str(aa_change))
    if match:
        aa_site = match.group(1)
    else:
        continue

    # Only count synonymous or nonsynonymous
    if syn_status not in ["synonymous", "nonsynonymous"]:
        continue

    # Initialize sample if needed
    if sample not in SNPs:
        SNPs[sample] = {g: [] for g in ["pb2", "pb1", "pa", "ha", "np", "na", "mp", "ns"]}

    if gene not in SNPs[sample]:
        continue

    # Add unique amino acid site
    if aa_site not in SNPs[sample][gene]:
        SNPs[sample][gene].append(aa_site)

# Convert to counts
SNP_counts = {
    sample: {gene: len(aa_sites) for gene, aa_sites in genes.items()}
    for sample, genes in SNPs.items()
}

print(SNP_counts)

{'c_com5': {'pb2': 0, 'pb1': 3, 'pa': 2, 'ha': 0, 'np': 0, 'na': 4, 'mp': 0, 'ns': 0}, 'c_com6': {'pb2': 1, 'pb1': 0, 'pa': 0, 'ha': 0, 'np': 1, 'na': 1, 'mp': 0, 'ns': 0}, 'c_lbm10': {'pb2': 1, 'pb1': 1, 'pa': 1, 'ha': 1, 'np': 2, 'na': 0, 'mp': 0, 'ns': 1}, 'c_lbm11': {'pb2': 0, 'pb1': 4, 'pa': 0, 'ha': 2, 'np': 0, 'na': 0, 'mp': 0, 'ns': 0}, 'c_lbm1': {'pb2': 0, 'pb1': 0, 'pa': 0, 'ha': 1, 'np': 2, 'na': 2, 'mp': 0, 'ns': 0}, 'c_lbm2': {'pb2': 3, 'pb1': 1, 'pa': 0, 'ha': 0, 'np': 3, 'na': 1, 'mp': 0, 'ns': 0}, 'c_lbm3': {'pb2': 0, 'pb1': 0, 'pa': 0, 'ha': 1, 'np': 0, 'na': 0, 'mp': 0, 'ns': 0}, 'c_lbm5': {'pb2': 2, 'pb1': 4, 'pa': 1, 'ha': 2, 'np': 2, 'na': 4, 'mp': 0, 'ns': 1}, 'c_lbm6': {'pb2': 0, 'pb1': 0, 'pa': 2, 'ha': 1, 'np': 2, 'na': 0, 'mp': 0, 'ns': 2}, 'c_lbm7': {'pb2': 1, 'pb1': 2, 'pa': 4, 'ha': 1, 'np': 0, 'na': 3, 'mp': 0, 'ns': 0}, 'c_lbm8': {'pb2': 1, 'pb1': 1, 'pa': 1, 'ha': 1, 'np': 4, 'na': 2, 'mp': 0, 'ns': 0}, 'c_lbm9': {'pb2': 2, 'pb1': 1, 'pa': 1, 'ha': 0, 'np': 2, 'na': 0, 'mp': 0, 'ns': 0}, 'cb_com1': {'pb2': 2, 'pb1': 2, 'pa': 4, 'ha': 0, 'np': 1, 'na': 0, 'mp': 1, 'ns': 1}, 'cb_com2': {'pb2': 1, 'pb1': 1, 'pa': 0, 'ha': 1, 'np': 1, 'na': 2, 'mp': 1, 'ns': 1}, 'cb_com3': {'pb2': 2, 'pb1': 1, 'pa': 0, 'ha': 4, 'np': 0, 'na': 0, 'mp': 0, 'ns': 0}, 'cb_com4': {'pb2': 0, 'pb1': 1, 'pa': 0, 'ha': 0, 'np': 0, 'na': 0, 'mp': 0, 'ns': 0}, 'ckr_com1': {'pb2': 4, 'pb1': 3, 'pa': 4, 'ha': 2, 'np': 5, 'na': 1, 'mp': 0, 'ns': 1}, 'ckr_com2': {'pb2': 2, 'pb1': 2, 'pa': 1, 'ha': 1, 'np': 4, 'na': 1, 'mp': 1, 'ns': 2}, 'ckr_com3': {'pb2': 2, 'pb1': 2, 'pa': 3, 'ha': 4, 'np': 3, 'na': 1, 'mp': 0, 'ns': 2}, 'd_com1': {'pb2': 3, 'pb1': 2, 'pa': 1, 'ha': 1, 'np': 1, 'na': 3, 'mp': 0, 'ns': 1}, 'd_com2': {'pb2': 3, 'pb1': 1, 'pa': 1, 'ha': 1, 'np': 2, 'na': 4, 'mp': 0, 'ns': 0}, 'd_com3': {'pb2': 0, 'pb1': 0, 'pa': 0, 'ha': 0, 'np': 0, 'na': 1, 'mp': 0, 'ns': 2}, 'd_lbm1': {'pb2': 3, 'pb1': 3, 'pa': 1, 'ha': 0, 'np': 3, 'na': 0, 'mp': 0, 'ns': 0}, 'd_lbm2': {'pb2': 4, 'pb1': 2, 'pa': 1, 'ha': 1, 'np': 3, 'na': 2, 'mp': 0, 'ns': 0}, 'd_lbm3': {'pb2': 1, 'pb1': 3, 'pa': 1, 'ha': 3, 'np': 1, 'na': 3, 'mp': 0, 'ns': 0}, 'd_lbm4': {'pb2': 2, 'pb1': 1, 'pa': 0, 'ha': 3, 'np': 2, 'na': 1, 'mp': 1, 'ns': 0}, 'g_com1': {'pb2': 0, 'pb1': 0, 'pa': 1, 'ha': 0, 'np': 0, 'na': 0, 'mp': 0, 'ns': 1}, 'g_com2': {'pb2': 2, 'pb1': 0, 'pa': 1, 'ha': 0, 'np': 0, 'na': 0, 'mp': 0, 'ns': 0}, 'g_lbm1': {'pb2': 1, 'pb1': 1, 'pa': 0, 'ha': 0, 'np': 0, 'na': 3, 'mp': 0, 'ns': 0}, 'gn_lbm1': {'pb2': 2, 'pb1': 3, 'pa': 1, 'ha': 0, 'np': 4, 'na': 3, 'mp': 0, 'ns': 0}, 'kc_com3': {'pb2': 1, 'pb1': 0, 'pa': 9, 'ha': 0, 'np': 0, 'na': 2, 'mp': 0, 'ns': 1}, 'kc_com4': {'pb2': 1, 'pb1': 2, 'pa': 2, 'ha': 0, 'np': 0, 'na': 0, 'mp': 0, 'ns': 0}, 'kc_com5': {'pb2': 0, 'pb1': 2, 'pa': 2, 'ha': 0, 'np': 1, 'na': 1, 'mp': 1, 'ns': 1}, 'kc_com6': {'pb2': 2, 'pb1': 2, 'pa': 3, 'ha': 0, 'np': 0, 'na': 3, 'mp': 0, 'ns': 3}, 'kc_com7': {'pb2': 1, 'pb1': 0, 'pa': 0, 'ha': 0, 'np': 1, 'na': 0, 'mp': 0, 'ns': 0}, 'kc_com8': {'pb2': 0, 'pb1': 1, 'pa': 0, 'ha': 0, 'np': 0, 'na': 0, 'mp': 0, 'ns': 0}}

In [29]:
# Divide each value by the corresponding value in sample_cvg_nt_int
divided_values = {
    sample: {
        gene: SNP_counts[sample][gene] / sample_cvg_nt_int[sample][gene]
        if sample_cvg_nt_int[sample][gene] != 0 else 0
        for gene in SNP_counts[sample]
    }
    for sample in SNP_counts
}

# Optional: round to 4 decimals
divided_values_rounded = {
    sample: {gene: round(value, 4) for gene, value in genes.items()}
    for sample, genes in divided_values.items()
}

print(divided_values_rounded)

{'c_com5': {'pb2': 0.0, 'pb1': 0.0013, 'pa': 0.0009, 'ha': 0.0, 'np': 0.0, 'na': 0.0027, 'mp': 0.0, 'ns': 0.0}, 'c_com6': {'pb2': 0.0004, 'pb1': 0.0, 'pa': 0.0, 'ha': 0.0, 'np': 0.0006, 'na': 0.0007, 'mp': 0.0, 'ns': 0.0}, 'c_lbm10': {'pb2': 0.0004, 'pb1': 0.0004, 'pa': 0.0004, 'ha': 0.0006, 'np': 0.0013, 'na': 0.0, 'mp': 0.0, 'ns': 0.0011}, 'c_lbm11': {'pb2': 0, 'pb1': 0.0018, 'pa': 0.0, 'ha': 0.0011, 'np': 0, 'na': 0, 'mp': 0, 'ns': 0.0}, 'c_lbm1': {'pb2': 0.0, 'pb1': 0.0, 'pa': 0.0, 'ha': 0.0006, 'np': 0.0013, 'na': 0.0014, 'mp': 0, 'ns': 0.0}, 'c_lbm2': {'pb2': 0.0013, 'pb1': 0.0004, 'pa': 0.0, 'ha': 0.0, 'np': 0.002, 'na': 0.0007, 'mp': 0.0, 'ns': 0.0}, 'c_lbm3': {'pb2': 0.0, 'pb1': 0.0, 'pa': 0.0, 'ha': 0.0006, 'np': 0.0, 'na': 0, 'mp': 0, 'ns': 0.0}, 'c_lbm5': {'pb2': 0.0009, 'pb1': 0.0017, 'pa': 0.0004, 'ha': 0.0011, 'np': 0.0013, 'na': 0.0027, 'mp': 0.0, 'ns': 0.0011}, 'c_lbm6': {'pb2': 0.0, 'pb1': 0.0, 'pa': 0.0009, 'ha': 0.0006, 'np': 0.0013, 'na': 0.0, 'mp': 0, 'ns': 0.0022}, 'c_lbm7': {'pb2': 0.0004, 'pb1': 0.0009, 'pa': 0.0018, 'ha': 0.0006, 'np': 0.0, 'na': 0.0021, 'mp': 0.0, 'ns': 0.0}, 'c_lbm8': {'pb2': 0.0004, 'pb1': 0.0004, 'pa': 0.0004, 'ha': 0.0006, 'np': 0.0026, 'na': 0.0014, 'mp': 0, 'ns': 0.0}, 'c_lbm9': {'pb2': 0.0009, 'pb1': 0.0004, 'pa': 0.0004, 'ha': 0.0, 'np': 0.0013, 'na': 0.0, 'mp': 0.0, 'ns': 0.0}, 'cb_com1': {'pb2': 0.0009, 'pb1': 0.0009, 'pa': 0.0018, 'ha': 0.0, 'np': 0.0006, 'na': 0.0, 'mp': 0.001, 'ns': 0.0011}, 'cb_com2': {'pb2': 0.0004, 'pb1': 0.0004, 'pa': 0.0, 'ha': 0.0006, 'np': 0.0006, 'na': 0.0014, 'mp': 0.001, 'ns': 0.0011}, 'cb_com3': {'pb2': 0.0009, 'pb1': 0.0004, 'pa': 0.0, 'ha': 0.0023, 'np': 0.0, 'na': 0.0, 'mp': 0.0, 'ns': 0.0}, 'cb_com4': {'pb2': 0.0, 'pb1': 0.0004, 'pa': 0.0, 'ha': 0.0, 'np': 0.0, 'na': 0.0, 'mp': 0.0, 'ns': 0.0}, 'ckr_com1': {'pb2': 0.0017, 'pb1': 0.0013, 'pa': 0.0018, 'ha': 0.0011, 'np': 0.0033, 'na': 0.0007, 'mp': 0.0, 'ns': 0.0011}, 'ckr_com2': {'pb2': 0.0009, 'pb1': 0.0009, 'pa': 0.0004, 'ha': 0.0006, 'np': 0.0026, 'na': 0.0007, 'mp': 0.001, 'ns': 0.0022}, 'ckr_com3': {'pb2': 0.0009, 'pb1': 0.0009, 'pa': 0.0013, 'ha': 0.0023, 'np': 0.002, 'na': 0.0007, 'mp': 0.0, 'ns': 0.0023}, 'd_com1': {'pb2': 0.0013, 'pb1': 0.0009, 'pa': 0.0004, 'ha': 0.0006, 'np': 0.0006, 'na': 0.0022, 'mp': 0.0, 'ns': 0.0011}, 'd_com2': {'pb2': 0.0013, 'pb1': 0.0004, 'pa': 0.0004, 'ha': 0.0006, 'np': 0.0013, 'na': 0.0029, 'mp': 0, 'ns': 0.0}, 'd_com3': {'pb2': 0.0, 'pb1': 0.0, 'pa': 0.0, 'ha': 0.0, 'np': 0, 'na': 0.0007, 'mp': 0.0, 'ns': 0.0022}, 'd_lbm1': {'pb2': 0.0024, 'pb1': 0.0013, 'pa': 0.0008, 'ha': 0.0, 'np': 0.0019, 'na': 0, 'mp': 0, 'ns': 0.0}, 'd_lbm2': {'pb2': 0.0032, 'pb1': 0.0009, 'pa': 0.0008, 'ha': 0.0006, 'np': 0.002, 'na': 0.0017, 'mp': 0, 'ns': 0.0}, 'd_lbm3': {'pb2': 0.0004, 'pb1': 0.0013, 'pa': 0.0008, 'ha': 0.0017, 'np': 0.0007, 'na': 0.0021, 'mp': 0.0, 'ns': 0.0}, 'd_lbm4': {'pb2': 0.0009, 'pb1': 0.0004, 'pa': 0.0, 'ha': 0.0017, 'np': 0.0013, 'na': 0.0007, 'mp': 0.001, 'ns': 0.0}, 'g_com1': {'pb2': 0.0, 'pb1': 0, 'pa': 0.0009, 'ha': 0.0, 'np': 0, 'na': 0, 'mp': 0.0, 'ns': 0.0011}, 'g_com2': {'pb2': 0.0016, 'pb1': 0, 'pa': 0.0005, 'ha': 0.0, 'np': 0, 'na': 0.0, 'mp': 0, 'ns': 0.0}, 'g_lbm1': {'pb2': 0.0009, 'pb1': 0.0004, 'pa': 0.0, 'ha': 0.0, 'np': 0.0, 'na': 0.0023, 'mp': 0, 'ns': 0.0}, 'gn_lbm1': {'pb2': 0.0009, 'pb1': 0.0013, 'pa': 0.0004, 'ha': 0.0, 'np': 0.0026, 'na': 0.0021, 'mp': 0.0, 'ns': 0.0}, 'kc_com3': {'pb2': 0.0004, 'pb1': 0.0, 'pa': 0.004, 'ha': 0.0, 'np': 0.0, 'na': 0.0014, 'mp': 0.0, 'ns': 0.0011}, 'kc_com4': {'pb2': 0.0004, 'pb1': 0.0009, 'pa': 0.0009, 'ha': 0.0, 'np': 0.0, 'na': 0.0, 'mp': 0.0, 'ns': 0.0}, 'kc_com5': {'pb2': 0.0, 'pb1': 0.0009, 'pa': 0.0009, 'ha': 0.0, 'np': 0.0006, 'na': 0.0007, 'mp': 0.001, 'ns': 0.0011}, 'kc_com6': {'pb2': 0.0016, 'pb1': 0.0009, 'pa': 0.0013, 'ha': 0.0, 'np': 0.0, 'na': 0.0021, 'mp': 0.0, 'ns': 0.0034}, 'kc_com7': {'pb2': 0.0008, 'pb1': 0.0, 'pa': 0.0, 'ha': 0.0, 'np': 0.0007, 'na': 0.0, 'mp': 0, 'ns': 0.0}, 'kc_com8': {'pb2': 0.0, 'pb1': 0.0004, 'pa': 0.0, 'ha': 0.0, 'np': 0.0, 'na': 0.0, 'mp': 0.0, 'ns': 0.0}}

In [31]:
# segment_to_gene = {
#     'ha': ['HA'],
#     'na': ['NA'],
#     'np': ['NP'],
#     'pa': ['PA'],
#     'pb1': ['PB1'],
#     'pb2': ['PB2'],
#     'mp': ['M1', 'M2'],
#     'ns': ['NS1', 'NEP']
# }
# snp_density = {}

# # Only use samples that exist in BOTH dictionaries
# common_samples = set(coverage_dict.keys()) & set(SNP_counts.keys())

# for sample in common_samples:
#     snp_density[sample] = {}

#     for segment, coverage_prop in coverage_dict[sample].items():

#         gene_len = gene_lengths.get(segment, 0)

#         # SNP dictionary uses uppercase gene names
#         snps = SNP_counts[sample].get(segment.upper(), 0)

#         if gene_len == 0 or coverage_prop == 0:
#             snp_density[sample][segment] = 0
#             continue

#         covered_nt = gene_len * coverage_prop
#         covered_kb = covered_nt / 1000

#         snp_density[sample][segment] = snps / covered_kb if covered_kb > 0 else 0

# for sample in snp_density:
#     for gene in snp_density[sample]:
#         snp_density[sample][gene] = round(float(snp_density[sample][gene]), 3)

# print(snp_density)

{'g_com1': {'ha': 0.0, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.885, 'pb1': 0.0, 'pb2': 0.0}, 'c_lbm8': {'ha': 0.563, 'mp': 0.0, 'na': 1.373, 'np': 2.606, 'ns': 0.0, 'pa': 0.449, 'pb1': 0.427, 'pb2': 0.427}, 'c_lbm11': {'ha': 1.129, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.0, 'pb1': 1.762, 'pb2': 0.0}, 'g_com2': {'ha': 0.0, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.474, 'pb1': 0.0, 'pb2': 1.605}, 'c_lbm10': {'ha': 1.126, 'mp': 0.0, 'na': 0.0, 'np': 1.287, 'ns': 0.0, 'pa': 0.896, 'pb1': 0.427, 'pb2': 0.427}, 'c_lbm3': {'ha': 0.563, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.0, 'pb2': 0.0}, 'c_lbm5': {'ha': 1.126, 'mp': 0.0, 'na': 3.432, 'np': 1.288, 'ns': 0.0, 'pa': 0.448, 'pb1': 2.136, 'pb2': 2.563}, 'ckr_com2': {'ha': 0.563, 'mp': 0.0, 'na': 0.726, 'np': 2.564, 'ns': 0.0, 'pa': 0.448, 'pb1': 0.854, 'pb2': 1.709}, 'c_lbm2': {'ha': 0.564, 'mp': 0.0, 'na': 0.73, 'np': 2.009, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.427, 'pb2': 1.735}, 'c_lbm7': {'ha': 1.689, 'mp': 0.0, 'na': 3.432, 'np': 0.0, 'ns': 0.0, 'pa': 1.791, 'pb1': 0.854, 'pb2': 1.282}, 'ckr_com1': {'ha': 1.126, 'mp': 0.0, 'na': 0.726, 'np': 3.901, 'ns': 0.0, 'pa': 2.687, 'pb1': 1.282, 'pb2': 3.419}, 'c_lbm1': {'ha': 0.563, 'mp': 0.0, 'na': 1.374, 'np': 1.305, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.0, 'pb2': 0.0}, 'c_lbm6': {'ha': 1.126, 'mp': 0.0, 'na': 0.0, 'np': 1.325, 'ns': 0.0, 'pa': 0.896, 'pb1': 0.427, 'pb2': 0.0}, 'd_lbm4': {'ha': 2.252, 'mp': 0.0, 'na': 0.689, 'np': 1.279, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.854, 'pb2': 1.288}, 'kc_com3': {'ha': 0.0, 'mp': 0.0, 'na': 1.373, 'np': 0.0, 'ns': 0.0, 'pa': 5.822, 'pb1': 0.427, 'pb2': 0.427}, 'd_com1': {'ha': 1.126, 'mp': 0.0, 'na': 4.36, 'np': 1.295, 'ns': 0.0, 'pa': 1.343, 'pb1': 1.709, 'pb2': 4.274}, 'ckr_com3': {'ha': 2.815, 'mp': 0.0, 'na': 0.727, 'np': 2.604, 'ns': 0.0, 'pa': 1.344, 'pb1': 1.282, 'pb2': 0.855}, 'd_com2': {'ha': 2.252, 'mp': 0.0, 'na': 2.905, 'np': 1.303, 'ns': 0.0, 'pa': 0.448, 'pb1': 1.282, 'pb2': 2.564}, 'd_lbm1': {'ha': 0.563, 'mp': 0.0, 'na': 0.0, 'np': 1.918, 'ns': 0.0, 'pa': 0.794, 'pb1': 1.282, 'pb2': 3.215}, 'cb_com3': {'ha': 2.252, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.854, 'pb2': 0.861}, 'd_com3': {'ha': 0.563, 'mp': 0.0, 'na': 0.726, 'np': 0.0, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.0, 'pb2': 0.0}, 'gn_lbm1': {'ha': 0.0, 'mp': 0.0, 'na': 2.059, 'np': 9.103, 'ns': 0.0, 'pa': 1.343, 'pb1': 2.563, 'pb2': 1.709}, 'g_lbm1': {'ha': 0.563, 'mp': 0.0, 'na': 2.268, 'np': 0.0, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.854, 'pb2': 0.943}, 'd_lbm2': {'ha': 0.563, 'mp': 0.0, 'na': 1.689, 'np': 1.97, 'ns': 0.0, 'pa': 0.794, 'pb1': 0.854, 'pb2': 4.032}, 'ckr_lbm1': {'ha': 0.0, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.427, 'pb2': 0.0}, 'cb_com1': {'ha': 1.126, 'mp': 0.0, 'na': 0.0, 'np': 0.639, 'ns': 0.0, 'pa': 2.239, 'pb1': 1.282, 'pb2': 0.854}, 'c_com6': {'ha': 1.126, 'mp': 0.0, 'na': 0.686, 'np': 0.639, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.854, 'pb2': 0.855}, 'kc_com4': {'ha': 0.0, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.896, 'pb1': 1.282, 'pb2': 0.431}, 'kc_com7': {'ha': 1.126, 'mp': 0.0, 'na': 0.0, 'np': 0.749, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.0, 'pb2': 1.605}, 'c_com5': {'ha': 0.563, 'mp': 0.0, 'na': 3.432, 'np': 0.0, 'ns': 0.0, 'pa': 0.896, 'pb1': 1.282, 'pb2': 0.0}, 'kc_com5': {'ha': 0.0, 'mp': 0.0, 'na': 0.687, 'np': 0.639, 'ns': 0.0, 'pa': 3.135, 'pb1': 0.854, 'pb2': 0.0}, 'kc_com8': {'ha': 0.0, 'mp': 0.0, 'na': 0.0, 'np': 0.654, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.427, 'pb2': 0.0}, 'd_lbm3': {'ha': 2.252, 'mp': 0.0, 'na': 2.059, 'np': 0.651, 'ns': 0.0, 'pa': 0.794, 'pb1': 1.282, 'pb2': 0.427}, 'cb_com4': {'ha': 1.126, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.427, 'pb2': 0.0}, 'c_com2': {'ha': 0.563, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.0, 'pb2': 0.427}, 'kc_com2': {'ha': 0.0, 'mp': 0.0, 'na': 0.0, 'np': 0.639, 'ns': 0.0, 'pa': 0.448, 'pb1': 0.0, 'pb2': 0.427}, 'cb_com2': {'ha': 1.126, 'mp': 0.0, 'na': 1.373, 'np': 0.641, 'ns': 0.0, 'pa': 0.0, 'pb1': 0.427, 'pb2': 0.427}, 'kc_com1': {'ha': 0.0, 'mp': 0.0, 'na': 0.0, 'np': 0.0, 'ns': 0.0, 'pa': 0.448, 'pb1': 0.0, 'pb2': 0.0}, 'c_lbm9': {'ha': 0.0, 'mp': 0.0, 'na': 0.0, 'np': 1.302, 'ns': 0.0, 'pa': 0.448, 'pb1': 0.427, 'pb2': 1.282}, 'kc_com6': {'ha': 0.0, 'mp': 0.0, 'na': 2.745, 'np': 0.0, 'ns': 0.0, 'pa': 2.239, 'pb1': 0.854, 'pb2': 2.406}}

In [ ]:
###OK NO THIS IS WRONG- what i want to do:
#take my gene lengths dict (nt length), multiply those lengths by the percentages of coverage for each gene for each sample,
##and then take those values (total nts with coverage) a

In [ ]:
# snp_densitySNP_counts

In [31]:
df_snp_cts = pd.DataFrame.from_dict(SNP_counts, orient='index')
df_snp_cts = df_snp_cts.reset_index()
df_snp_cts = df_snp_cts.rename(columns={'index': 'sample_id'})
df_snp_cts['total_snps'] = df_snp_cts.iloc[:, 1:9].sum(axis=1)

df_snp_cts

   sample_id  pb2  pb1  pa  ha  np  na  mp  ns  total_snps
0     c_com5    0    3   2   0   0   4   0   0           9
1     c_com6    1    0   0   0   1   1   0   0           3
2    c_lbm10    1    1   1   1   2   0   0   1           7
3    c_lbm11    0    4   0   2   0   0   0   0           6
4     c_lbm1    0    0   0   1   2   2   0   0           5
5     c_lbm2    3    1   0   0   3   1   0   0           8
6     c_lbm3    0    0   0   1   0   0   0   0           1
7     c_lbm5    2    4   1   2   2   4   0   1          16
8     c_lbm6    0    0   2   1   2   0   0   2           7
9     c_lbm7    1    2   4   1   0   3   0   0          11
10    c_lbm8    1    1   1   1   4   2   0   0          10
11    c_lbm9    2    1   1   0   2   0   0   0           6
12   cb_com1    2    2   4   0   1   0   1   1          11
13   cb_com2    1    1   0   1   1   2   1   1           8
14   cb_com3    2    1   0   4   0   0   0   0           7
15   cb_com4    0    1   0   0   0   0   0   0           1
16  ckr_com1    4    3   4   2   5   1   0   1          20
17  ckr_com2    2    2   1   1   4   1   1   2          14
18  ckr_com3    2    2   3   4   3   1   0   2          17
19    d_com1    3    2   1   1   1   3   0   1          12
20    d_com2    3    1   1   1   2   4   0   0          12
21    d_com3    0    0   0   0   0   1   0   2           3
22    d_lbm1    3    3   1   0   3   0   0   0          10
23    d_lbm2    4    2   1   1   3   2   0   0          13
24    d_lbm3    1    3   1   3   1   3   0   0          12
25    d_lbm4    2    1   0   3   2   1   1   0          10
26    g_com1    0    0   1   0   0   0   0   1           2
27    g_com2    2    0   1   0   0   0   0   0           3
28    g_lbm1    1    1   0   0   0   3   0   0           5
29   gn_lbm1    2    3   1   0   4   3   0   0          13
30   kc_com3    1    0   9   0   0   2   0   1          13
31   kc_com4    1    2   2   0   0   0   0   0           5
32   kc_com5    0    2   2   0   1   1   1   1           8
33   kc_com6    2    2   3   0   0   3   0   3          13
34   kc_com7    1    0   0   0   1   0   0   0           2
35   kc_com8    0    1   0   0   0   0   0   0           1

In [32]:
df_snp_cvg_nt = pd.DataFrame.from_dict(sample_cvg_nt_int, orient='index')
df_snp_cvg_nt = df_snp_cvg_nt.reset_index()
df_snp_cvg_nt = df_snp_cvg_nt.rename(columns={'index': 'sample_id'})
df_snp_cvg_nt['total_nts'] = df_snp_cvg_nt.iloc[:, 1:9].sum(axis=1)

df_snp_cvg_nt

   sample_id    ha    mp    na    np   ns    pa   pb1   pb2  total_nts
0     d_lbm2  1776     0  1184  1523  890  1259  2341  1240      10213
1     d_lbm3  1776    23  1457  1535  890  1260  2341  2341      11623
2     d_lbm4  1776   997  1451  1564  890  2227  2341  2330      13576
3    kc_com3  1776   933  1457  1564  890  2233  2341  2341      13535
4    kc_com4  1776   944  1457  1555  890  2232  2341  2318      13513
5     d_com3  1776    30  1377     0  890  1208  1498  2337       9116
6    kc_com5  1776   963  1456  1564  890  2233  2341  2321      13544
7    kc_com2  1776   972  1457  1564  890  2233  1482  2341      12715
8     d_com2  1776     0  1377  1535  889  2233  2341  2340      12491
9    cb_com1  1776   995  1442  1564  890  2233  2341  2341      13582
10    c_com3  1045     0     0     0  285  1260  1084  1240       4914
11    g_com1  1776    66     0     0  890  1130     0  1242       5104
12    c_com4     0     0     0     0    0     0     0     0          0
13  ckr_com3  1776   899  1376  1536  887  2232  2341  2340      13387
14    c_com5  1776   967  1457  1560  889  2233  2341  2340      13563
15    c_com2  1776     0  1319   677  890  2233  2341  2341      11577
16  ckr_com2  1776  1004  1377  1560  889  2233  2341  2340      13520
17   gn_lbm1  1776   969  1457  1538  889  2233  2341  2340      13543
18    c_lbm2  1772    36  1370  1493  890  1259  2341  2306      11467
19    c_lbm5  1776   977  1457  1553  890  2233  2341  2341      13568
20    g_lbm1  1775     0  1323    23  885  1260  2341  1060       8667
21    c_lbm3  1776     0     0   150  890  1259  2340  1464       7879
22    d_lbm1  1776     0     0  1564  890  1259  2341  1244       9074
23   c_lbm10  1776   976  1457  1554  890  2233  2341  2341      13568
24   kc_com7  1776     0  1457  1335  890  2233  1663  1246      10600
25    d_com1  1776   936  1376  1544  889  2233  2341  2340      13435
26   c_lbm11  1771     0     0     0  885  1259  2270     0       6185
27   kc_com1  1776   965  1457  1564  890  2232  2341  2341      13566
28   kc_com6  1776   179  1457  1535  890  2233  2341  1247      11658
29   kc_com8  1776    33  1456  1528  890  2233  2341  1246      11503
30    g_com2  1776     0  1229     0  890  2110     0  1246       7251
31   cb_com2  1776   968  1457  1560  890  2233  2341  2340      13565
32  ckr_com1  1776   958  1377  1538  889  2233  2341  2340      13452
33   cb_com3  1776   555  1457  1527  890  2233  2341  2323      13102
34    c_com1  1776     0     0     0  888  2227  1096  1206       7193
35   cb_com4  1776     7  1457  1497  890  2233  2341  2298      12499
36    c_com6  1776   950  1457  1564  890  2233  2341  2340      13551
37  ckr_lbm1  1776     0   302  1454  890  1258  2341  2115      10136
38    c_lbm6  1776     0  1457  1509  889  2233  2341  2341      12546
39    c_lbm1  1776     0  1456  1533  889  2227  2341  1359      11581
40    c_lbm8  1776     0  1457  1535  890  2227  2341  2340      12566
41    c_lbm9  1776   376  1456  1536  890  2233  2341  2341      12949
42    c_lbm7  1776   172  1457  1536  889  2233  2341  2341      12745

In [33]:
nts_snps = pd.merge(df_snp_cvg_nt[['sample_id', 'total_nts']], df_snp_cts[['sample_id', 'total_snps']], on='sample_id', how='left')
nts_snps['snps_per_1kb'] = nts_snps['total_snps']/nts_snps['total_nts']*1000
nts_snps.fillna(0, inplace=True)
nts_snps

   sample_id  total_nts  total_snps  snps_per_1kb
0     d_lbm2      10213        13.0      1.272887
1     d_lbm3      11623        12.0      1.032436
2     d_lbm4      13576        10.0      0.736594
3    kc_com3      13535        13.0      0.960473
4    kc_com4      13513         5.0      0.370014
5     d_com3       9116         3.0      0.329092
6    kc_com5      13544         8.0      0.590667
7    kc_com2      12715         0.0      0.000000
8     d_com2      12491        12.0      0.960692
9    cb_com1      13582        11.0      0.809895
10    c_com3       4914         0.0      0.000000
11    g_com1       5104         2.0      0.391850
12    c_com4          0         0.0      0.000000
13  ckr_com3      13387        17.0      1.269889
14    c_com5      13563         9.0      0.663570
15    c_com2      11577         0.0      0.000000
16  ckr_com2      13520        14.0      1.035503
17   gn_lbm1      13543        13.0      0.959905
18    c_lbm2      11467         8.0      0.697654
19    c_lbm5      13568        16.0      1.179245
20    g_lbm1       8667         5.0      0.576901
21    c_lbm3       7879         1.0      0.126920
22    d_lbm1       9074        10.0      1.102050
23   c_lbm10      13568         7.0      0.515920
24   kc_com7      10600         2.0      0.188679
25    d_com1      13435        12.0      0.893189
26   c_lbm11       6185         6.0      0.970089
27   kc_com1      13566         0.0      0.000000
28   kc_com6      11658        13.0      1.115114
29   kc_com8      11503         1.0      0.086934
30    g_com2       7251         3.0      0.413736
31   cb_com2      13565         8.0      0.589753
32  ckr_com1      13452        20.0      1.486768
33   cb_com3      13102         7.0      0.534270
34    c_com1       7193         0.0      0.000000
35   cb_com4      12499         1.0      0.080006
36    c_com6      13551         3.0      0.221386
37  ckr_lbm1      10136         0.0      0.000000
38    c_lbm6      12546         7.0      0.557947
39    c_lbm1      11581         5.0      0.431742
40    c_lbm8      12566        10.0      0.795798
41    c_lbm9      12949         6.0      0.463356
42    c_lbm7      12745        11.0      0.863084

In [34]:
# nts_snps.to_csv('../../seq/analysis/output_dfs/snps-per-1kb-allcomm_2pct.tsv', sep='\t')
nts_snps.to_csv('../output_dfs/2026-05-05-snps-per-1kb-allcomm.tsv', sep='\t')